
import type { Checklist } from '@/app/types';

export const initialChecklists: Checklist[] = [
  {
    id: 'cl-1',
    title: '🔐 Authentication & Onboarding',
    items: [
      { id: 'item-1-1', text: 'Welcome screen displays correctly', status: 'pending' },
      { id: 'item-1-2', text: 'Onboarding flow works (first-time users)', status: 'pending' },
      { id: 'item-1-3', text: 'Skip onboarding works', status: 'pending' },
      { id: 'item-1-4', text: 'Onboarding state persists correctly', status: 'pending' },
      { id: 'item-1-5', text: 'Login with email works', status: 'pending' },
      { id: 'item-1-6', text: 'Login with phone number works', status: 'pending' },
      { id: 'item-1-7', text: 'Signup/Registration flow completes successfully', status: 'pending' },
      { id: 'item-1-8', text: 'Phone verification (OTP) sends correctly', status: 'pending' },
      { id: 'item-1-9', text: 'OTP verification works', status: 'pending' },
      { id: 'item-1-10', text: 'OTP resend functionality works', status: 'pending' },
      { id: 'item-1-11', text: 'OTP expiration handling works', status: 'pending' },
      { id: 'item-1-12', text: 'Password reset flow works', status: 'pending' },
      { id: 'item-1-13', text: 'Forgot password email/SMS sends', status: 'pending' },
      { id: 'item-1-14', text: 'Password reset link works', status: 'pending' },
      { id: 'item-1-15', text: 'Error messages display correctly for invalid credentials', status: 'pending' },
      { id: 'item-1-16', text: 'User session persists after app restart', status: 'pending' },
      { id: 'item-1-17', text: 'Token refresh works automatically', status: 'pending' },
      { id: 'item-1-18', text: '401 errors trigger proper logout', status: 'pending' },
      { id: 'item-1-19', text: 'Logout clears all user data', status: 'pending' },
      { id: 'item-1-20', text: 'Logout clears RTK Query cache', status: 'pending' },
      { id: 'item-1-21', text: 'Logout clears AsyncStorage/EncryptedStorage', status: 'pending' },
      { id: 'item-1-22', text: 'Multiple device login handling works', status: 'pending' },
    ],
  },
  {
    id: 'cl-2',
    title: '🏠 Home Screen & Discovery',
    items: [
      { id: 'item-2-1', text: 'Home screen loads without errors', status: 'pending' },
      { id: 'item-2-2', text: 'Products/listings load correctly', status: 'pending' },
      { id: 'item-2-3', text: 'Infinite scroll/pagination works smoothly', status: 'pending' },
      { id: 'item-2-4', text: 'Pull-to-refresh works', status: 'pending' },
      { id: 'item-2-5', text: 'Images load properly (no broken images)', status: 'pending' },
      { id: 'item-2-6', text: 'Loading states display correctly', status: 'pending' },
      { id: 'item-2-7', text: 'Empty states display when no products', status: 'pending' },
      { id: 'item-2-8', text: 'Error states display with retry option', status: 'pending' },
      { id: 'item-2-9', text: 'Filter modal opens/closes correctly', status: 'pending' },
      { id: 'item-2-10', text: 'Category filter works', status: 'pending' },
      { id: 'item-2-11', text: 'Brand filter works', status: 'pending' },
      { id: 'item-2-12', text: 'Price range slider works', status: 'pending' },
      { id: 'item-2-13', text: 'Shipping options filter works', status: 'pending' },
      { id: 'item-2-14', text: 'Product condition filter works', status: 'pending' },
      { id: 'item-2-15', text: 'Sort by options work', status: 'pending' },
      { id: 'item-2-16', text: 'Multiple filters can be applied together', status: 'pending' },
      { id: 'item-2-17', text: 'Filter reset works', status: 'pending' },
      { id: 'item-2-18', text: 'Filter state persists during navigation', status: 'pending' },
      { id: 'item-2-19', text: 'Applied filters display correctly', status: 'pending' },
      { id: 'item-2-20', text: 'Search screen opens from bottom tab', status: 'pending' },
      { id: 'item-2-21', text: 'Text search works', status: 'pending' },
      { id: 'item-2-22', text: 'Search results load correctly', status: 'pending' },
      { id: 'item-2-23', text: 'Search history works', status: 'pending' },
      { id: 'item-2-24', text: 'Recent searches display', status: 'pending' },
      { id: 'item-2-25', text: 'Clear search history works', status: 'pending' },
      { id: 'item-2-26', text: 'Visual search works (if applicable)', status: 'pending' },
      { id: 'item-2-27', text: 'Search suggestions appear', status: 'pending' },
      { id: 'item-2-28', text: 'Empty search results display correctly', status: 'pending' },
      { id: 'item-2-29', text: 'Categories screen loads', status: 'pending' },
      { id: 'item-2-30', text: 'Category navigation works', status: 'pending' },
      { id: 'item-2-31', text: 'Category products load', status: 'pending' },
      { id: 'item-2-32', text: 'Subcategories display correctly', status: 'pending' },
      { id: 'item-2-33', text: 'Category images load', status: 'pending' },
      { id: 'item-2-34', text: 'Nearby products feature works', status: 'pending' },
    ],
  },
  {
    id: 'cl-3',
    title: '📦 Product Listings',
    items: [
      { id: 'item-3-1', text: 'Product detail screen loads', status: 'pending' },
      { id: 'item-3-2', text: 'Product images display in gallery', status: 'pending' },
      { id: 'item-3-3', text: 'Image swiper/zoom works', status: 'pending' },
      { id: 'item-3-4', text: 'Product information displays correctly', status: 'pending' },
      { id: 'item-3-5', text: 'Price displays correctly', status: 'pending' },
      { id: 'item-3-6', text: 'Quantity selector works', status: 'pending' },
      { id: 'item-3-7', text: 'Product description displays', status: 'pending' },
      { id: 'item-3-8', text: 'Seller information displays', status: 'pending' },
      { id: 'item-3-9', text: 'Related products load', status: 'pending' },
      { id: 'item-3-10', text: 'Share functionality works', status: 'pending' },
      { id: 'item-3-11', text: 'Car product detail screen loads', status: 'pending' },
      { id: 'item-3-12', text: 'Car images display correctly', status: 'pending' },
      { id: 'item-3-13', text: 'Car specifications display', status: 'pending' },
      { id: 'item-3-14', text: 'Car features display', status: 'pending' },
      { id: 'item-3-15', text: 'Car condition displays', status: 'pending' },
      { id: 'item-3-16', text: 'Buy now works for cars', status: 'pending' },
      { id: 'item-3-17', text: 'Make offer works for cars', status: 'pending' },
      { id: 'item-3-18', text: 'Real estate detail screen loads', status: 'pending' },
      { id: 'item-3-19', text: 'Property images display', status: 'pending' },
      { id: 'item-3-20', text: 'Property details display', status: 'pending' },
      { id: 'item-3-21', text: 'Property features display', status: 'pending' },
      { id: 'item-3-22', text: 'Location/map displays correctly', status: 'pending' },
      { id: 'item-3-23', text: 'Property specifications display', status: 'pending' },
      { id: 'item-3-24', text: 'Buy now works for real estate', status: 'pending' },
      { id: 'item-3-25', text: 'Make offer works for real estate', status: 'pending' },
      { id: 'item-3-26', text: 'Add to wishlist works', status: 'pending' },
      { id: 'item-3-27', text: 'Remove from wishlist works', status: 'pending' },
      { id: 'item-3-28', text: 'Wishlist optimistic updates work', status: 'pending' },
      { id: 'item-3-29', text: 'Add to cart works (if applicable)', status: 'pending' },
      { id: 'item-3-30', text: 'Buy now button works', status: 'pending' },
      { id: 'item-3-31', text: 'Make offer button works', status: 'pending' },
      { id: 'item-3-32', text: 'Send offer functionality works', status: 'pending' },
      { id: 'item-3-33', text: 'Offer validation works', status: 'pending' },
      { id: 'item-3-34', text: 'Chat with seller works', status: 'pending' },
      { id: 'item-3-35', text: 'Follow seller works', status: 'pending' },
      { id: 'item-3-36', text: 'Share product works', status: 'pending' },
      { id: 'item-3-37', text: 'Report product works (if applicable)', status: 'pending' },
      { id: 'item-3-38', text: 'Product card displays correctly', status: 'pending' },
      { id: 'item-3-39', text: 'Product card images load', status: 'pending' },
      { id: 'item-3-40', text: 'Product card navigation works', status: 'pending' },
      { id: 'item-3-41', text: 'Product card interactions work', status: 'pending' },
    ],
  },
  {
    id: 'cl-4',
    title: '🛒 Shopping & Checkout',
    items: [
        { id: 'item-4-1', text: 'Add items to cart', status: 'pending' },
        { id: 'item-4-2', text: 'Remove items from cart', status: 'pending' },
        { id: 'item-4-3', text: 'Update quantities in cart', status: 'pending' },
        { id: 'item-4-4', text: 'Cart persists after app restart', status: 'pending' },
        { id: 'item-4-5', text: 'Cart total calculates correctly', status: 'pending' },
        { id: 'item-4-6', text: 'Cart empty state displays', status: 'pending' },
        { id: 'item-4-7', text: 'Checkout screen loads', status: 'pending' },
        { id: 'item-4-8', text: 'Address selection works', status: 'pending' },
        { id: 'item-4-9', text: 'Add new address from checkout works', status: 'pending' },
        { id: 'item-4-10', text: 'Delivery type selection works (pickup/shipping)', status: 'pending' },
        { id: 'item-4-11', text: 'Shipping carrier selection works', status: 'pending' },
        { id: 'item-4-12', text: 'Shipping cost calculates correctly', status: 'pending' },
        { id: 'item-4-13', text: 'Delivery instructions can be added', status: 'pending' },
        { id: 'item-4-14', text: 'Payment method selection works', status: 'pending' },
        { id: 'item-4-15', text: 'Saved payment cards display', status: 'pending' },
        { id: 'item-4-16', text: 'Add new payment card works', status: 'pending' },
        { id: 'item-4-17', text: 'Order summary displays correctly', status: 'pending' },
        { id: 'item-4-18', text: 'Price breakdown displays correctly', status: 'pending' },
        { id: 'item-4-19', text: 'Tax calculation works', status: 'pending' },
        { id: 'item-4-20', text: 'Shipping cost displays', status: 'pending' },
        { id: 'item-4-21', text: 'Total price calculates correctly', status: 'pending' },
        { id: 'item-4-22', text: 'Submit order works', status: 'pending' },
        { id: 'item-4-23', text: 'Order submission loading state works', status: 'pending' },
        { id: 'item-4-24', text: 'Order confirmation screen displays', status: 'pending' },
        { id: 'item-4-25', text: 'Payment WebView loads', status: 'pending' },
        { id: 'item-4-26', text: 'PayTabs integration works', status: 'pending' },
        { id: 'item-4-27', text: 'Card payment processing works', status: 'pending' },
        { id: 'item-4-28', text: 'Payment success handling works', status: 'pending' },
        { id: 'item-4-29', text: 'Payment failure handling works', status: 'pending' },
        { id: 'item-4-30', text: 'Payment cancellation works', status: 'pending' },
        { id: 'item-4-31', text: 'Saved cards work for payment', status: 'pending' },
        { id: 'item-4-32', text: 'New card entry works', status: 'pending' },
        { id: 'item-4-33', text: 'Payment tokens save correctly', status: 'pending' },
        { id: 'item-4-34', text: 'Installments screen loads', status: 'pending' },
        { id: 'item-4-35', text: 'Installment plans display', status: 'pending' },
        { id: 'item-4-36', text: 'Installment selection works', status: 'pending' },
        { id: 'item-4-37', text: 'Installment calculation works', status: 'pending' },
    ]
  },
  {
    id: 'cl-5',
    title: '📋 Order Management',
    items: [
        { id: 'item-5-1', text: 'Buyer orders screen loads', status: 'pending' },
        { id: 'item-5-2', text: 'Order list displays correctly', status: 'pending' },
        { id: 'item-5-3', text: 'Order status displays correctly', status: 'pending' },
        { id: 'item-5-4', text: 'Order details screen loads', status: 'pending' },
        { id: 'item-5-5', text: 'Order information displays correctly', status: 'pending' },
        { id: 'item-5-6', text: 'Order items display correctly', status: 'pending' },
        { id: 'item-5-7', text: 'Order tracking works', status: 'pending' },
        { id: 'item-5-8', text: 'Order history loads', status: 'pending' },
        { id: 'item-5-9', text: 'Filter orders by status works', status: 'pending' },
        { id: 'item-5-10', text: 'Seller orders screen loads', status: 'pending' },
        { id: 'item-5-11', text: 'Seller order list displays', status: 'pending' },
        { id: 'item-5-12', text: 'Order status updates work', status: 'pending' },
        { id: 'item-5-13', text: 'Order details display correctly', status: 'pending' },
        { id: 'item-5-14', text: 'Order fulfillment works', status: 'pending' },
        { id: 'item-5-15', text: 'Order tracking updates work', status: 'pending' },
        { id: 'item-5-16', text: 'Order filters work', status: 'pending' },
        { id: 'item-5-17', text: 'Track order screen loads', status: 'pending' },
        { id: 'item-5-18', text: 'Order status updates display', status: 'pending' },
        { id: 'item-5-19', text: 'Tracking information displays', status: 'pending' },
        { id: 'item-5-20', text: 'Delivery updates work', status: 'pending' },
        { id: 'item-5-21', text: 'Order submission screen displays', status: 'pending' },
        { id: 'item-5-22', text: 'Order confirmation displays', status: 'pending' },
        { id: 'item-5-23', text: 'Order number displays correctly', status: 'pending' },
        { id: 'item-5-24', text: 'Navigation after order works', status: 'pending' },
    ]
  },
  {
    id: 'cl-6',
    title: '🔄 Return Orders',
    items: [
        { id: 'item-6-1', text: 'Return order instructions screen loads', status: 'pending' },
        { id: 'item-6-2', text: 'Return request can be created', status: 'pending' },
        { id: 'item-6-3', text: 'Return order details display', status: 'pending' },
        { id: 'item-6-4', text: 'Return dispute can be created', status: 'pending' },
        { id: 'item-6-5', text: 'Return review request works', status: 'pending' },
        { id: 'item-6-6', text: 'Return status updates display', status: 'pending' },
        { id: 'item-6-7', text: 'Seller return order details load', status: 'pending' },
        { id: 'item-6-8', text: 'Return order invoice displays', status: 'pending' },
        { id: 'item-6-9', text: 'Return approval/rejection works', status: 'pending' },
        { id: 'item-6-10', text: 'Return status updates work', status: 'pending' },
    ],
  },
  {
    id: 'cl-7',
    title: '💰 Offers & Bidding',
    items: [
        { id: 'item-7-1', text: 'Offers screen loads', status: 'pending' },
        { id: 'item-7-2', text: 'Offers list displays', status: 'pending' },
        { id: 'item-7-3', text: 'Offer details screen loads', status: 'pending' },
        { id: 'item-7-4', text: 'Make offer works', status: 'pending' },
        { id: 'item-7-5', text: 'Offer acceptance works', status: 'pending' },
        { id: 'item-7-6', text: 'Offer rejection works', status: 'pending' },
        { id: 'item-7-7', text: 'Offer counter-offer works', status: 'pending' },
        { id: 'item-7-8', text: 'Offer expiration handling works', status: 'pending' },
        { id: 'item-7-9', text: 'Offer notifications work', status: 'pending' },
        { id: 'item-7-10', text: 'Bidding history screen loads', status: 'pending' },
        { id: 'item-7-11', text: 'Bidding history details display', status: 'pending' },
        { id: 'item-7-12', text: 'Place bid works', status: 'pending' },
        { id: 'item-7-13', text: 'Bid updates display', status: 'pending' },
        { id: 'item-7-14', text: 'Bid notifications work', status: 'pending' },
    ],
  },
  {
    id: 'cl-8',
    title: '👤 Profile Management',
    items: [
        { id: 'item-8-1', text: 'Profile screen loads', status: 'pending' },
        { id: 'item-8-2', text: 'Profile information displays correctly', status: 'pending' },
        { id: 'item-8-3', text: 'Profile image displays', status: 'pending' },
        { id: 'item-8-4', text: 'Edit profile works', status: 'pending' },
        { id: 'item-8-5', text: 'Profile image upload works', status: 'pending' },
        { id: 'item-8-6', text: 'Profile update saves correctly', status: 'pending' },
        { id: 'item-8-7', text: 'Profile validation works', status: 'pending' },
        { id: 'item-8-8', text: 'Seller profile screen loads', status: 'pending' },
        { id: 'item-8-9', text: 'Seller personal info displays', status: 'pending' },
        { id: 'item-8-10', text: 'Edit seller profile works', status: 'pending' },
        { id: 'item-8-11', text: 'Seller profile image upload works', status: 'pending' },
        { id: 'item-8-12', text: 'Business verification works', status: 'pending' },
        { id: 'item-8-13', text: 'Seller profile update saves', status: 'pending' },
        { id: 'item-8-14', text: 'Shipping services configuration works', status: 'pending' },
        { id: 'item-8-15', text: 'Public profile screen loads', status: 'pending' },
        { id: 'item-8-16', text: 'Public profile information displays', status: 'pending' },
        { id: 'item-8-17', text: 'Follow/unfollow from public profile works', status: 'pending' },
        { id: 'item-8-18', text: 'Seller listings display on public profile', status: 'pending' },
        { id: 'item-8-19', text: 'Change password works', status: 'pending' },
        { id: 'item-8-20', text: 'Update phone number works', status: 'pending' },
        { id: 'item-8-21', text: 'Phone OTP for update works', status: 'pending' },
        { id: 'item-8-22', text: 'Update email works', status: 'pending' },
        { id: 'item-8-23', text: 'Email OTP for update works', status: 'pending' },
        { id: 'item-8-24', text: 'Profile settings save correctly', status: 'pending' },
    ],
  },
  {
    id: 'cl-9',
    title: '📍 Address Management',
    items: [
        { id: 'item-9-1', text: 'Saved addresses screen loads', status: 'pending' },
        { id: 'item-9-2', text: 'Address list displays', status: 'pending' },
        { id: 'item-9-3', text: 'Add address works', status: 'pending' },
        { id: 'item-9-4', text: 'Edit address works', status: 'pending' },
        { id: 'item-9-5', text: 'Delete address works', status: 'pending' },
        { id: 'item-9-6', text: 'Set default address works', status: 'pending' },
        { id: 'item-9-7', text: 'Address validation works', status: 'pending' },
        { id: 'item-9-8', text: 'State selection works', status: 'pending' },
        { id: 'item-9-9', text: 'City selection by state works', status: 'pending' },
        { id: 'item-9-10', text: 'Address autocomplete works (if applicable)', status: 'pending' },
        { id: 'item-9-11', text: 'Map selection for address works (if applicable)', status: 'pending' },
    ],
  },
  {
    id: 'cl-10',
    title: '🏪 Seller Features',
    items: [
        { id: 'item-10-1', text: 'Seller dashboard loads', status: 'pending' },
        { id: 'item-10-2', text: 'Dashboard statistics display correctly', status: 'pending' },
        { id: 'item-10-3', text: 'Active listings count displays', status: 'pending' },
        { id: 'item-10-4', text: 'Orders count displays', status: 'pending' },
        { id: 'item-10-5', text: 'Revenue displays (if applicable)', status: 'pending' },
        { id: 'item-10-6', text: 'Dashboard refreshes correctly', status: 'pending' },
        { id: 'item-10-7', text: 'Mode switching (buyer/seller) works', status: 'pending' },
        { id: 'item-10-8', text: 'Seller listings screen loads', status: 'pending' },
        { id: 'item-10-9', text: 'Active listings display', status: 'pending' },
        { id: 'item-10-10', text: 'Draft listings display', status: 'pending' },
        { id: 'item-10-11', text: 'Sold listings display', status: 'pending' },
        { id: 'item-10-12', text: 'Listing status filters work', status: 'pending' },
        { id: 'item-10-13', text: 'Listing details screen loads', status: 'pending' },
        { id: 'item-10-14', text: 'Edit listing works', status: 'pending' },
        { id: 'item-10-15', text: 'Delete listing works', status: 'pending' },
        { id: 'item-10-16', text: 'Listing statistics display', status: 'pending' },
        { id: 'item-10-17', text: 'Start listing screen loads', status: 'pending' },
        { id: 'item-10-18', text: 'Listing type selection works', status: 'pending' },
        { id: 'item-10-19', text: 'About product form works', status: 'pending' },
        { id: 'item-10-20', text: 'Describe item form works', status: 'pending' },
        { id: 'item-10-21', text: 'Describe condition works', status: 'pending' },
        { id: 'item-10-22', text: 'Additional information form works', status: 'pending' },
        { id: 'item-10-23', text: 'AI upload works (if applicable)', status: 'pending' },
        { id: 'item-10-24', text: 'Form validation works', status: 'pending' },
        { id: 'item-10-25', text: 'Navigation between steps works', status: 'pending' },
        { id: 'item-10-26', text: 'Media upload works', status: 'pending' },
        { id: 'item-10-27', text: 'Image selection works', status: 'pending' },
        { id: 'item-10-28', text: 'Image preview works', status: 'pending' },
        { id: 'item-10-29', text: 'Video upload works (if applicable)', status: 'pending' },
        { id: 'item-10-30', text: 'Media deletion works', status: 'pending' },
        { id: 'item-10-31', text: 'Product description editor works', status: 'pending' },
        { id: 'item-10-32', text: 'Standout features work', status: 'pending' },
        { id: 'item-10-33', text: 'Set price works', status: 'pending' },
        { id: 'item-10-34', text: 'Shipping type selection works', status: 'pending' },
        { id: 'item-10-35', text: 'Shipping carrier selection works', status: 'pending' },
        { id: 'item-10-36', text: 'Shipping cost calculation works', status: 'pending' },
        { id: 'item-10-37', text: 'Return policy settings work', status: 'pending' },
        { id: 'item-10-38', text: 'Listing type selection works', status: 'pending' },
        { id: 'item-10-39', text: 'Address selection works', status: 'pending' },
        { id: 'item-10-40', text: 'New address creation works', status: 'pending' },
        { id: 'item-10-41', text: 'Seller profile edit works', status: 'pending' },
        { id: 'item-10-42', text: 'Account verification check works', status: 'pending' },
        { id: 'item-10-43', text: 'Review listing works', status: 'pending' },
        { id: 'item-10-44', text: 'Confirm listing works', status: 'pending' },
        { id: 'item-10-45', text: 'Tax details form works', status: 'pending' },
        { id: 'item-10-46', text: 'Publish listing works', status: 'pending' },
        { id: 'item-10-47', text: 'Listing confirmation displays', status: 'pending' },
        { id: 'item-10-48', text: 'Car listing flow works', status: 'pending' },
        { id: 'item-10-49', text: 'All car-specific steps work', status: 'pending' },
        { id: 'item-10-50', text: 'Car details form works', status: 'pending' },
        { id: 'item-10-51', text: 'Car specifications form works', status: 'pending' },
        { id: 'item-10-52', text: 'Car media upload works', status: 'pending' },
        { id: 'item-10-53', text: 'Car listing publishes successfully', status: 'pending' },
        { id: 'item-10-54', text: 'Real estate listing flow works', status: 'pending' },
        { id: 'item-10-55', text: 'Property selection works', status: 'pending' },
        { id: 'item-10-56', text: 'Property information form works', status: 'pending' },
        { id: 'item-10-57', text: 'Property features form works', status: 'pending' },
        { id: 'item-10-58', text: 'Property details form works', status: 'pending' },
        { id: 'item-10-59', text: 'Property location works', status: 'pending' },
        { id: 'item-10-60', text: 'Property images upload works', status: 'pending' },
        { id: 'item-10-61', text: 'Preview and publish works', status: 'pending' },
        { id: 'item-10-62', text: 'Listing drawer opens/closes', status: 'pending' },
        { id: 'item-10-63', text: 'Step navigation in drawer works', status: 'pending' },
        { id: 'item-10-64', text: 'Drawer displays current step', status: 'pending' },
        { id: 'item-10-65', text: 'Step selection from drawer works', status: 'pending' },
        { id: 'item-10-66', text: 'Seller wallet screen loads', status: 'pending' },
        { id: 'item-10-67', text: 'Wallet balance displays', status: 'pending' },
        { id: 'item-10-68', text: 'Transaction history displays', status: 'pending' },
        { id: 'item-10-69', text: 'Withdrawal works (if applicable)', status: 'pending' },
        { id: 'item-10-70', text: 'Wallet transactions filter work', status: 'pending' },
    ],
  },
  {
    id: 'cl-11',
    title: '💬 Messaging & Chat',
    items: [
        { id: 'item-11-1', text: 'Messages screen loads', status: 'pending' },
        { id: 'item-11-2', text: 'Message list displays', status: 'pending' },
        { id: 'item-11-3', text: 'Unread message count displays', status: 'pending' },
        { id: 'item-11-4', text: 'Message notifications work', status: 'pending' },
        { id: 'item-11-5', text: 'Chat details screen loads', status: 'pending' },
        { id: 'item-11-6', text: 'Send message works', status: 'pending' },
        { id: 'item-11-7', text: 'Receive message works', status: 'pending' },
        { id: 'item-11-8', text: 'Message images work', status: 'pending' },
        { id: 'item-11-9', text: 'Message read status works', status: 'pending' },
        { id: 'item-11-10', text: 'Typing indicator works (if applicable)', status: 'pending' },
        { id: 'item-11-11', text: 'Chat details screen loads', status: 'pending' },
        { id: 'item-11-12', text: 'Message history loads', status: 'pending' },
        { id: 'item-11-13', text: 'Send text message works', status: 'pending' },
        { id: 'item-11-14', text: 'Send image works', status: 'pending' },
        { id: 'item-11-15', text: 'Message timestamps display', status: 'pending' },
        { id: 'item-11-16', text: 'Message status indicators work', status: 'pending' },
    ],
  },
  {
    id: 'cl-12',
    title: '👥 Social Features',
    items: [
        { id: 'item-12-1', text: 'Follow user works', status: 'pending' },
        { id: 'item-12-2', text: 'Unfollow user works', status: 'pending' },
        { id: 'item-12-3', text: 'Follow optimistic updates work', status: 'pending' },
        { id: 'item-12-4', text: 'Follow count updates correctly', status: 'pending' },
        { id: 'item-12-5', text: 'Follow status displays correctly', status: 'pending' },
        { id: 'item-12-6', text: 'Followers screen loads', status: 'pending' },
        { id: 'item-12-7', text: 'Followers list displays', status: 'pending' },
        { id: 'item-12-8', text: 'Following list displays', status: 'pending' },
        { id: 'item-12-9', text: 'Remove follower works', status: 'pending' },
        { id: 'item-12-10', text: 'Followers count displays correctly', status: 'pending' },
        { id: 'item-12-11', text: 'Blocked users screen loads', status: 'pending' },
        { id: 'item-12-12', text: 'Block user works', status: 'pending' },
        { id: 'item-12-13', text: 'Unblock user works', status: 'pending' },
        { id: 'item-12-14', text: 'Blocked users list displays', status: 'pending' },
        { id: 'item-12-15', text: 'Blocked users cannot message', status: 'pending' },
    ],
  },
  {
    id: 'cl-13',
    title: '❤️ Wishlist',
    items: [
        { id: 'item-13-1', text: 'Wishlist screen loads', status: 'pending' },
        { id: 'item-13-2', text: 'Wishlist items display', status: 'pending' },
        { id: 'item-13-3', text: 'Add to wishlist works', status: 'pending' },
        { id: 'item-13-4', text: 'Remove from wishlist works', status: 'pending' },
        { id: 'item-13-5', text: 'Wishlist optimistic updates work', status: 'pending' },
        { id: 'item-13-6', text: 'Wishlist persists correctly', status: 'pending' },
        { id: 'item-13-7', text: 'Empty wishlist state displays', status: 'pending' },
        { id: 'item-13-8', text: 'Navigate to product from wishlist works', status: 'pending' },
    ],
  },
  {
    id: 'cl-14',
    title: '📚 Browser History',
    items: [
        { id: 'item-14-1', text: 'Browser history screen loads', status: 'pending' },
        { id: 'item-14-2', text: 'History items display', status: 'pending' },
        { id: 'item-14-3', text: 'Clear history works', status: 'pending' },
        { id: 'item-14-4', text: 'Navigate from history works', status: 'pending' },
        { id: 'item-14-5', text: 'History persists correctly', status: 'pending' },
    ],
  },
  {
    id: 'cl-15',
    title: '🔔 Notifications',
    items: [
        { id: 'item-15-1', text: 'Notifications screen loads', status: 'pending' },
        { id: 'item-15-2', text: 'Notification list displays', status: 'pending' },
        { id: 'item-15-3', text: 'Notification types display correctly', status: 'pending' },
        { id: 'item-15-4', text: 'Notification tap navigation works', status: 'pending' },
        { id: 'item-15-5', text: 'Mark as read works', status: 'pending' },
        { id: 'item-15-6', text: 'Clear notifications works', status: 'pending' },
        { id: 'item-15-7', text: 'Push notifications received', status: 'pending' },
        { id: 'item-15-8', text: 'Push notification tap works', status: 'pending' },
        { id: 'item-15-9', text: 'Notification badges update', status: 'pending' },
    ],
  },
  {
    id: 'cl-16',
    title: '📸 Camera & Media',
    items: [
        { id: 'item-16-1', text: 'Camera screen opens', status: 'pending' },
        { id: 'item-16-2', text: 'Take photo works', status: 'pending' },
        { id: 'item-16-3', text: 'Select from gallery works', status: 'pending' },
        { id: 'item-16-4', text: 'Custom camera works', status: 'pending' },
        { id: 'item-16-5', text: 'Image preview works', status: 'pending' },
        { id: 'item-16-6', text: 'Image cropping works (if applicable)', status: 'pending' },
        { id: 'item-16-7', text: 'Multiple image selection works', status: 'pending' },
        { id: 'item-16-8', text: 'Image upload works', status: 'pending' },
        { id: 'item-16-9', text: 'Visual search info screen loads', status: 'pending' },
        { id: 'item-16-10', text: 'Visual search works', status: 'pending' },
        { id: 'item-16-11', text: 'Search results from image display', status: 'pending' },
    ],
  },
  {
    id: 'cl-17',
    title: '🗺️ Navigation & UI',
    items: [
        { id: 'item-17-1', text: 'Home tab works', status: 'pending' },
        { id: 'item-17-2', text: 'Categories/Shop tab works', status: 'pending' },
        { id: 'item-17-3', text: 'Add listing button works (center)', status: 'pending' },
        { id: 'item-17-4', text: 'Listings tab works (seller mode)', status: 'pending' },
        { id: 'item-17-5', text: 'Orders tab works (seller mode)', status: 'pending' },
        { id: 'item-17-6', text: 'Profile tab works', status: 'pending' },
        { id: 'item-17-7', text: 'Tab switching works smoothly', status: 'pending' },
        { id: 'item-17-8', text: 'Tab badges display correctly', status: 'pending' },
        { id: 'item-17-9', text: 'Tab indicator animates correctly', status: 'pending' },
        { id: 'item-17-10', text: 'Mode switching (buyer/seller) updates tabs', status: 'pending' },
        { id: 'item-17-11', text: 'Drawer opens/closes', status: 'pending' },
        { id: 'item-17-12', text: 'Drawer swipe works (on allowed screens)', status: 'pending' },
        { id: 'item-17-13', text: 'Drawer content displays correctly', status: 'pending' },
        { id: 'item-17-14', text: 'Drawer navigation works', status: 'pending' },
        { id: 'item-17-15', text: 'Drawer closes on navigation', status: 'pending' },
        { id: 'item-17-16', text: 'Screen navigation works', status: 'pending' },
        { id: 'item-17-17', text: 'Back button works', status: 'pending' },
        { id: 'item-17-18', text: 'Deep linking works', status: 'pending' },
        { id: 'item-17-19', text: 'Navigation transitions are smooth', status: 'pending' },
        { id: 'item-17-20', text: 'No navigation loops', status: 'pending' },
        { id: 'item-17-21', text: 'Screen params pass correctly', status: 'pending' },
        { id: 'item-17-22', text: 'Add listing modal opens', status: 'pending' },
        { id: 'item-17-23', text: 'Normal product option works', status: 'pending' },
        { id: 'item-17-24', text: 'Vehicles option works', status: 'pending' },
        { id: 'item-17-25', text: 'Real estate option works', status: 'pending' },
        { id: 'item-17-26', text: 'Modal closes after selection', status: 'pending' },
    ],
  },
  {
    id: 'cl-18',
    title: '🌐 Internationalization',
    items: [
        { id: 'item-18-1', text: 'Language switching works', status: 'pending' },
        { id: 'item-18-2', text: 'Arabic (RTL) layout displays correctly', status: 'pending' },
        { id: 'item-18-3', text: 'English (LTR) layout displays correctly', status: 'pending' },
        { id: 'item-18-4', text: 'Text alignment correct in RTL', status: 'pending' },
        { id: 'item-18-5', text: 'Icons flip correctly in RTL', status: 'pending' },
        { id: 'item-18-6', text: 'Navigation flows correctly in RTL', status: 'pending' },
        { id: 'item-18-7', text: 'All strings are translated', status: 'pending' },
        { id: 'item-18-8', text: 'No hardcoded strings', status: 'pending' },
        { id: 'item-18-9', text: 'Date/time formats localized', status: 'pending' },
        { id: 'item-18-10', text: 'Number formats localized', status: 'pending' },
        { id: 'item-18-11', text: 'Currency displays correctly', status: 'pending' },
    ],
  },
  {
    id: 'cl-19',
    title: '🎨 UI/UX & Performance',
    items: [
        { id: 'item-19-1', text: 'App works on different screen sizes', status: 'pending' },
        { id: 'item-19-2', text: 'Tablet layout works correctly', status: 'pending' },
        { id: 'item-19-3', text: 'Phone layout works correctly', status: 'pending' },
        { id: 'item-19-4', text: 'Text is readable on all devices', status: 'pending' },
        { id: 'item-19-5', text: 'Images scale correctly', status: 'pending' },
        { id: 'item-19-6', text: 'Layout doesn\'t break', status: 'pending' },
        { id: 'item-19-7', text: 'Safe area insets work (notches, etc.)', status: 'pending' },
        { id: 'item-19-8', text: 'Light theme displays correctly', status: 'pending' },
        { id: 'item-19-9', text: 'Dark theme displays correctly', status: 'pending' },
        { id: 'item-19-10', text: 'Theme switching works (if applicable)', status: 'pending' },
        { id: 'item-19-11', text: 'Colors are consistent', status: 'pending' },
        { id: 'item-19-12', text: 'Fonts load correctly', status: 'pending' },
        { id: 'item-19-13', text: 'No style overflows', status: 'pending' },
        { id: 'item-19-14', text: 'App launches in < 3 seconds', status: 'pending' },
        { id: 'item-19-15', text: 'No laggy animations', status: 'pending' },
        { id: 'item-19-16', text: 'List scrolling is smooth', status: 'pending' },
        { id: 'item-19-17', text: 'Images load efficiently', status: 'pending' },
        { id: 'item-19-18', text: 'No memory leaks', status: 'pending' },
        { id: 'item-19-19', text: 'No unnecessary re-renders', status: 'pending' },
        { id: 'item-19-20', text: 'Bundle size is optimized', status: 'pending' },
        { id: 'item-19-21', text: 'Loading indicators display', status: 'pending' },
        { id: 'item-19-22', text: 'Skeleton screens work', status: 'pending' },
        { id: 'item-19-23', text: 'Loading states don\'t block UI', status: 'pending' },
        { id: 'item-19-24', text: 'Error states display with retry', status: 'pending' },
    ],
  },
    {
    id: 'cl-20',
    title: '🔧 RTK Query & State Management',
    items: [
        { id: 'item-20-1', text: 'All queries cache correctly', status: 'pending' },
        { id: 'item-20-2', text: 'Mutations invalidate correct tags', status: 'pending' },
        { id: 'item-20-3', text: 'Optimistic updates work for: Follow/unfollow', status: 'pending' },
        { id: 'item-20-4', text: 'Optimistic updates work for: Wishlist add/remove', status: 'pending' },
        { id: 'item-20-5', text: 'Optimistic updates work for: Like/unlike (if applicable)', status: 'pending' },
        { id: 'item-20-6', text: 'Pagination works with serializeQueryArgs', status: 'pending' },
        { id: 'item-20-7', text: 'Cache resets on logout', status: 'pending' },
        { id: 'item-20-8', text: 'No manual refetching in components', status: 'pending' },
        { id: 'item-20-9', text: 'Error states handled correctly', status: 'pending' },
        { id: 'item-20-10', text: 'Loading states handled correctly', status: 'pending' },
        { id: 'item-20-11', text: 'Offline mode handled gracefully', status: 'pending' },
        { id: 'item-20-12', text: 'Network errors show user-friendly messages', status: 'pending' },
        { id: 'item-20-13', text: 'Retry mechanism works', status: 'pending' },
        { id: 'item-20-14', text: 'No API calls in useEffect (only RTK Query)', status: 'pending' },
    ],
  },
  {
    id: 'cl-21',
    title: '🔒 Security & Data',
    items: [
        { id: 'item-21-1', text: 'API keys not exposed', status: 'pending' },
        { id: 'item-21-2', text: 'Sensitive data encrypted in storage', status: 'pending' },
        { id: 'item-21-3', text: 'HTTPS used for all API calls', status: 'pending' },
        { id: 'item-21-4', text: 'Token storage is secure (EncryptedStorage)', status: 'pending' },
        { id: 'item-21-5', text: 'No debug logs in production build', status: 'pending' },
        { id: 'item-21-6', text: 'Code obfuscation enabled (if applicable)', status: 'pending' },
        { id: 'item-21-7', text: 'Critical data persists after app restart', status: 'pending' },
        { id: 'item-21-8', text: 'AsyncStorage works correctly', status: 'pending' },
        { id: 'item-21-9', text: 'EncryptedStorage works correctly', status: 'pending' },
        { id: 'item-21-10', text: 'Redux state persists where needed', status: 'pending' },
        { id: 'item-21-11', text: 'No data loss on app kill/restart', status: 'pending' },
    ],
  },
  {
    id: 'cl-22',
    title: '🐛 Error Handling',
    items: [
        { id: 'item-22-1', text: 'All error states have UI feedback', status: 'pending' },
        { id: 'item-22-2', text: 'Error messages are user-friendly', status: 'pending' },
        { id: 'item-22-3', text: 'No crashes on API errors', status: 'pending' },
        { id: 'item-22-4', text: 'Network errors handled gracefully', status: 'pending' },
        { id: 'item-22-5', text: 'Validation errors display correctly', status: 'pending' },
        { id: 'item-22-6', text: 'Form errors highlight correctly', status: 'pending' },
        { id: 'item-22-7', text: 'No unhandled promise rejections', status: 'pending' },
        { id: 'item-22-8', text: 'No null/undefined crashes', status: 'pending' },
        { id: 'item-22-9', text: 'Array/object access is safe', status: 'pending' },
        { id: 'item-22-10', text: 'All async operations have error handling', status: 'pending' },
    ],
  },
  {
    id: 'cl-23',
    title: '📱 Platform-Specific',
    items: [
        { id: 'item-23-1', text: 'App works on iOS 13+ (check minimum)', status: 'pending' },
        { id: 'item-23-2', text: 'Tested on iPhone (various sizes)', status: 'pending' },
        { id: 'item-23-3', text: 'Tested on iPad (if supported)', status: 'pending' },
        { id: 'item-23-4', text: 'Push notifications work', status: 'pending' },
        { id: 'item-23-5', text: 'App icons correct', status: 'pending' },
        { id: 'item-23-6', text: 'Splash screens correct', status: 'pending' },
        { id: 'item-23-7', text: 'Info.plist permissions correct', status: 'pending' },
        { id: 'item-23-8', text: 'Privacy permissions requested correctly', status: 'pending' },
        { id: 'item-23-9', text: 'App Store screenshots ready', status: 'pending' },
        { id: 'item-23-10', text: 'App works on Android 8+ (check minimum)', status: 'pending' },
        { id: 'item-23-11', text: 'Tested on various screen sizes', status: 'pending' },
        { id: 'item-23-12', text: 'Tested on various Android versions', status: 'pending' },
        { id: 'item-23-13', text: 'Push notifications work', status: 'pending' },
        { id: 'item-23-14', text: 'App icons correct', status: 'pending' },
        { id: 'item-23-15', text: 'Splash screens correct', status: 'pending' },
        { id: 'item-23-16', text: 'Permissions requested correctly', status: 'pending' },
        { id: 'item-23-17', text: 'Back button behavior correct', status: 'pending' },
        { id: 'item-23-18', text: 'Play Store screenshots ready', status: 'pending' },
        { id: 'item-23-19', text: 'ProGuard rules correct (if enabled)', status: 'pending' },
    ],
  },
  {
    id: 'cl-24',
    title: '🏗️ Build & Configuration',
    items: [
        { id: 'item-24-1', text: 'Production build created successfully', status: 'pending' },
        { id: 'item-24-2', text: 'Version number incremented', status: 'pending' },
        { id: 'item-24-3', text: 'Build number incremented', status: 'pending' },
        { id: 'item-24-4', text: 'Bundle identifier/package name correct', status: 'pending' },
        { id: 'item-24-5', text: 'Signing certificates valid', status: 'pending' },
        { id: 'item-24-6', text: 'Keystore files secure and backed up', status: 'pending' },
        { id: 'item-24-7', text: 'Environment variables set correctly', status: 'pending' },
        { id: 'item-24-8', text: 'API endpoints point to production', status: 'pending' },
        { id: 'item-24-9', text: 'Debug mode disabled', status: 'pending' },
        { id: 'item-24-10', text: 'No console.log statements', status: 'pending' },
        { id: 'item-24-11', text: 'No debug code left in', status: 'pending' },
        { id: 'item-24-12', text: 'No TODO comments for critical features', status: 'pending' },
        { id: 'item-24-13', text: 'Code follows project style guide', status: 'pending' },
        { id: 'item-24-14', text: 'No linter errors', status: 'pending' },
        { id: 'item-24-15', text: 'No TypeScript errors (if applicable)', status: 'pending' },
    ],
  },
  {
    id: 'cl-25',
    title: '🧪 Testing',
    items: [
        { id: 'item-25-1', text: 'Tested on physical iOS device', status: 'pending' },
        { id: 'item-25-2', text: 'Tested on physical Android device', status: 'pending' },
        { id: 'item-25-3', text: 'Tested on multiple device models', status: 'pending' },
        { id: 'item-25-4', text: 'Tested on different OS versions', status: 'pending' },
        { id: 'item-25-5', text: 'Tested with slow network (3G)', status: 'pending' },
        { id: 'item-25-6', text: 'Tested with no network (offline)', status: 'pending' },
        { id: 'item-25-7', text: 'Tested with airplane mode toggle', status: 'pending' },
        { id: 'item-25-8', text: 'Complete buyer flow: Browse → Product → Checkout → Order', status: 'pending' },
        { id: 'item-25-9', text: 'Complete seller flow: Create Listing → Publish → Manage Orders', status: 'pending' },
        { id: 'item-25-10', text: 'Complete offer flow: Make Offer → Accept → Checkout', status: 'pending' },
        { id: 'item-25-11', text: 'Complete return flow: Request Return → Process Return', status: 'pending' },
        { id: 'item-25-12', text: 'Complete profile setup flow', status: 'pending' },
        { id: 'item-25-13', text: 'Complete authentication flow', status: 'pending' },
        { id: 'item-25-14', text: 'Edge cases tested', status: 'pending' },
        { id: 'item-25-15', text: 'Stress testing (rapid interactions)', status: 'pending' },
        { id: 'item-25-16', text: 'Long session testing (1+ hours)', status: 'pending' },
    ],
  },
  {
    id: 'cl-26',
    title: '📦 App Store Requirements',
    items: [
        { id: 'item-26-1', text: 'App Store Connect configured', status: 'pending' },
        { id: 'item-26-2', text: 'App description ready', status: 'pending' },
        { id: 'item-26-3', text: 'Screenshots for all required sizes', status: 'pending' },
        { id: 'item-26-4', text: 'Privacy policy URL provided', status: 'pending' },
        { id: 'item-26-5', text: 'Support URL provided', status: 'pending' },
        { id: 'item-26-6', text: 'Age rating correct', status: 'pending' },
        { id: 'item-26-7', text: 'App Review Information complete', status: 'pending' },
        { id: 'item-26-8', text: 'TestFlight build tested', status: 'pending' },
        { id: 'item-26-9', text: 'Play Console configured', status: 'pending' },
        { id: 'item-26-10', text: 'App description ready', status: 'pending' },
        { id: 'item-26-11', text: 'Screenshots ready', status: 'pending' },
        { id: 'item-26-12', text: 'Feature graphic ready', status: 'pending' },
        { id: 'item-26-13', text: 'Privacy policy URL provided', status: 'pending' },
        { id: 'item-26-14', text: 'Content rating complete', status: 'pending' },
        { id: 'item-26-15', text: 'Internal testing track tested', status: 'pending' },
    ],
  },
  {
    id: 'cl-27',
    title: '📊 Monitoring & Analytics',
    items: [
        { id: 'item-27-1', text: 'Analytics events fire correctly', status: 'pending' },
        { id: 'item-27-2', text: 'User actions tracked', status: 'pending' },
        { id: 'item-27-3', text: 'Conversion events tracked', status: 'pending' },
        { id: 'item-27-4', text: 'Error events tracked', status: 'pending' },
        { id: 'item-27-5', text: 'Screen views tracked', status: 'pending' },
        { id: 'item-27-6', text: 'Crash reporting configured (Sentry)', status: 'pending' },
        { id: 'item-27-7', text: 'Performance monitoring enabled', status: 'pending' },
        { id: 'item-27-8', text: 'Error alerts configured', status: 'pending' },
        { id: 'item-27-9', text: 'Release tracking enabled', status: 'pending' },
        { id: 'item-27-10', text: 'Source maps uploaded', status: 'pending' },
    ],
  },
  {
    id: 'cl-28',
    title: '🚀 Release Day',
    items: [
        { id: 'item-28-1', text: 'Final production build created', status: 'pending' },
        { id: 'item-28-2', text: 'Build tested one more time', status: 'pending' },
        { id: 'item-28-3', text: 'Version numbers verified', status: 'pending' },
        { id: 'item-28-4', text: 'Release notes finalized', status: 'pending' },
        { id: 'item-28-5', text: 'Team notified of release', status: 'pending' },
        { id: 'item-28-6', text: 'Support channels ready', status: 'pending' },
        { id: 'item-28-7', text: 'Monitor crash reports (first 24 hours)', status: 'pending' },
        { id: 'item-28-8', text: 'Monitor error rates', status: 'pending' },
        { id: 'item-28-9', text: 'Monitor user feedback', status: 'pending' },
        { id: 'item-28-10', text: 'Monitor app store reviews', status: 'pending' },
        { id: 'item-28-11', text: 'Monitor analytics for anomalies', status: 'pending' },
        { id: 'item-28-12', text: 'Monitor API error rates', status: 'pending' },
        { id: 'item-28-13', text: 'Check Sentry for new errors', status: 'pending' },
        { id: 'item-28-14', text: 'Review performance metrics', status: 'pending' },
    ],
  },
  {
    id: 'cl-29',
    title: '🔄 Rollback Plan',
    items: [
        { id: 'item-29-1', text: 'Identify the issue', status: 'pending' },
        { id: 'item-29-2', text: 'Assess severity', status: 'pending' },
        { id: 'item-29-3', text: 'Decide on rollback', status: 'pending' },
        { id: 'item-29-4', text: 'Prepare hotfix (if needed)', status: 'pending' },
        { id: 'item-29-5', text: 'Execute rollback', status: 'pending' },
        { id: 'item-29-6', text: 'Communicate to users', status: 'pending' },
        { id: 'item-29-7', text: 'Fix issue in development', status: 'pending' },
        { id: 'item-29-8', text: 'Test fix thoroughly', status: 'pending' },
        { id: 'item-29-9', text: 'Release hotfix', status: 'pending' },
    ],
  }
];
