
import type { Checklist } from '@/app/types';

export const initialChecklists: Checklist[] = [
  {
    id: 'cl-1',
    title: '🔐 Authentication & Onboarding',
    items: [
      { id: 'item-1-1', text: 'Welcome screen loads with language selection modal', status: 'pending' },
      { id: 'item-1-2', text: 'Language selection persists (Arabic/English) in AsyncStorage', status: 'pending' },
      { id: 'item-1-3', text: 'Feature carousel slides display with pagination dots', status: 'pending' },
      { id: 'item-1-4', text: 'Carousel swipe navigation works smoothly', status: 'pending' },
      { id: 'item-1-5', text: 'Login main screen loads with all login options (Email, Phone, Google, Apple)', status: 'pending' },
      { id: 'item-1-6', text: 'Login with email form validates email format and password', status: 'pending' },
      { id: 'item-1-7', text: 'Login with email submits and authenticates successfully', status: 'pending' },
      { id: 'item-1-8', text: 'Login with phone number form validates phone format', status: 'pending' },
      { id: 'item-1-9', text: 'Login with phone triggers OTP send', status: 'pending' },
      { id: 'item-1-10', text: 'Google Sign-In flow completes successfully', status: 'pending' },
      { id: 'item-1-11', text: 'Apple Sign-In flow completes successfully', status: 'pending' },
      { id: 'item-1-12', text: 'Signup form validates all fields (name, email, phone, password)', status: 'pending' },
      { id: 'item-1-13', text: 'Signup registration completes and triggers verification', status: 'pending' },
      { id: 'item-1-14', text: 'Phone verification screen loads with correct phone number', status: 'pending' },
      { id: 'item-1-15', text: 'OTP verification input accepts 4/6 digit code', status: 'pending' },
      { id: 'item-1-16', text: 'OTP verification succeeds with valid code', status: 'pending' },
      { id: 'item-1-17', text: 'OTP resend button works with countdown timer', status: 'pending' },
      { id: 'item-1-18', text: 'OTP expiration displays error and allows resend', status: 'pending' },
      { id: 'item-1-19', text: 'Forget password email screen loads and validates email', status: 'pending' },
      { id: 'item-1-20', text: 'Forget password phone screen loads and sends OTP', status: 'pending' },
      { id: 'item-1-21', text: 'Reset password screen validates new password and confirm match', status: 'pending' },
      { id: 'item-1-22', text: 'Password changed confirmation screen displays', status: 'pending' },
      { id: 'item-1-23', text: 'Session expired screen displays and redirects to login', status: 'pending' },
      { id: 'item-1-24', text: 'Error messages display for invalid credentials', status: 'pending' },
      { id: 'item-1-25', text: 'User session persists in EncryptedStorage after app restart', status: 'pending' },
      { id: 'item-1-26', text: 'Token auto-refresh works on 401 response', status: 'pending' },
      { id: 'item-1-27', text: 'Expired token triggers proper logout flow', status: 'pending' },
      { id: 'item-1-28', text: 'Logout clears EncryptedStorage (USERINFO)', status: 'pending' },
      { id: 'item-1-29', text: 'Logout clears AsyncStorage user data', status: 'pending' },
      { id: 'item-1-30', text: 'Logout resets RTK Query cache', status: 'pending' },
      { id: 'item-1-31', text: 'Logout navigates back to WelcomeScreen', status: 'pending' },
      { id: 'item-1-32', text: 'AsyncStorage.hasOnboarded flag set correctly after first login', status: 'pending' },
    ],
  },
  {
    id: 'cl-2',
    title: '🏠 Home Screen & Discovery',
    items: [
      { id: 'item-2-1', text: 'Home screen loads without errors', status: 'pending' },
      { id: 'item-2-2', text: 'HomeHeader displays with notification badge count', status: 'pending' },
      { id: 'item-2-3', text: 'Search bar in header opens SearchScreen on tap', status: 'pending' },
      { id: 'item-2-4', text: 'Hero carousel (HeroScrolling) auto-scrolls and swipes', status: 'pending' },
      { id: 'item-2-5', text: 'Flash sale section displays with CountdownTimer', status: 'pending' },
      { id: 'item-2-6', text: 'Flash sale countdown timer ticks correctly', status: 'pending' },
      { id: 'item-2-7', text: 'Main banner swiper auto-scrolls promotional banners', status: 'pending' },
      { id: 'item-2-8', text: 'City-based swipers load products by location', status: 'pending' },
      { id: 'item-2-9', text: 'Brand section carousel displays and scrolls', status: 'pending' },
      { id: 'item-2-10', text: 'Product grid sections render with correct category titles', status: 'pending' },
      { id: 'item-2-11', text: 'Sale banner section displays promotions', status: 'pending' },
      { id: 'item-2-12', text: 'Dynamic sections from API render via SectionRenderer', status: 'pending' },
      { id: 'item-2-13', text: 'Pull-to-refresh reloads home data', status: 'pending' },
      { id: 'item-2-14', text: 'Infinite scroll/pagination loads more products', status: 'pending' },
      { id: 'item-2-15', text: 'Product images load via FastImage (no broken images)', status: 'pending' },
      { id: 'item-2-16', text: 'Loading/skeleton states display while data fetches', status: 'pending' },
      { id: 'item-2-17', text: 'Empty states display when no products available', status: 'pending' },
      { id: 'item-2-18', text: 'Error states display with retry option', status: 'pending' },
      { id: 'item-2-19', text: 'Update modal shows when new version available', status: 'pending' },
      { id: 'item-2-20', text: 'Whats New modal displays after app update', status: 'pending' },
      { id: 'item-2-21', text: 'Onboarding goal survey modal shows for new users', status: 'pending' },
      { id: 'item-2-22', text: 'Wishlist toggle on product cards works from home', status: 'pending' },
      { id: 'item-2-23', text: 'Product card tap navigates to correct detail screen', status: 'pending' },
      { id: 'item-2-24', text: 'See All button navigates to full category listing', status: 'pending' },
    ],
  },
  {
    id: 'cl-3',
    title: '🔍 Search & Filtering',
    items: [
      { id: 'item-3-1', text: 'Search screen opens from bottom tab / home header', status: 'pending' },
      { id: 'item-3-2', text: 'Text search input works and submits query', status: 'pending' },
      { id: 'item-3-3', text: 'Search results load correctly with product cards', status: 'pending' },
      { id: 'item-3-4', text: 'Search suggestions appear while typing', status: 'pending' },
      { id: 'item-3-5', text: 'Recent search history displays', status: 'pending' },
      { id: 'item-3-6', text: 'Clear search history works', status: 'pending' },
      { id: 'item-3-7', text: 'Empty search results display correctly', status: 'pending' },
      { id: 'item-3-8', text: 'Visual search info screen loads', status: 'pending' },
      { id: 'item-3-9', text: 'Visual search (image-based) works end-to-end', status: 'pending' },
      { id: 'item-3-10', text: 'Visual search results display matching products', status: 'pending' },
      { id: 'item-3-11', text: 'GlobalFilterModal opens from filter button', status: 'pending' },
      { id: 'item-3-12', text: 'Category filter works via CustomCategoryModal', status: 'pending' },
      { id: 'item-3-13', text: 'Brand filter works via CustomBrandModal', status: 'pending' },
      { id: 'item-3-14', text: 'Price range slider (PriceSlider) works', status: 'pending' },
      { id: 'item-3-15', text: 'Product condition filter works', status: 'pending' },
      { id: 'item-3-16', text: 'Shipping options filter works', status: 'pending' },
      { id: 'item-3-17', text: 'Sort by options (relevance, price, newest, rating) work', status: 'pending' },
      { id: 'item-3-18', text: 'Multiple filters can be combined together', status: 'pending' },
      { id: 'item-3-19', text: 'Applied filters display as chips/tags', status: 'pending' },
      { id: 'item-3-20', text: 'Filter reset clears all applied filters', status: 'pending' },
      { id: 'item-3-21', text: 'Filter state persists during navigation', status: 'pending' },
      { id: 'item-3-22', text: 'ListingsGridFilterModal works for grid view filtering', status: 'pending' },
      { id: 'item-3-23', text: 'ListingsGridFilterButtons quick filter buttons work', status: 'pending' },
      { id: 'item-3-24', text: 'NearbyProducts screen loads location-based results', status: 'pending' },
    ],
  },
  {
    id: 'cl-4',
    title: '📂 Categories & Browsing',
    items: [
      { id: 'item-4-1', text: 'Categories screen loads from bottom tab', status: 'pending' },
      { id: 'item-4-2', text: 'Category list displays with images', status: 'pending' },
      { id: 'item-4-3', text: 'Category tap navigates to CategoryProducts screen', status: 'pending' },
      { id: 'item-4-4', text: 'Subcategories display correctly within category', status: 'pending' },
      { id: 'item-4-5', text: 'Category products load and display in grid/list', status: 'pending' },
      { id: 'item-4-6', text: 'Category products pagination works', status: 'pending' },
      { id: 'item-4-7', text: 'Board screen loads with community content', status: 'pending' },
      { id: 'item-4-8', text: 'Board comments display with nested threads', status: 'pending' },
      { id: 'item-4-9', text: 'Board comment voting (like) works', status: 'pending' },
      { id: 'item-4-10', text: 'Board comment sorting works (newest/helpful)', status: 'pending' },
    ],
  },
  {
    id: 'cl-5',
    title: '📦 Product Detail (Standard)',
    items: [
      { id: 'item-5-1', text: 'Product detail screen loads with correct product data', status: 'pending' },
      { id: 'item-5-2', text: 'Product image carousel displays and swipes', status: 'pending' },
      { id: 'item-5-3', text: 'Image pinch-to-zoom gesture works', status: 'pending' },
      { id: 'item-5-4', text: 'Image tap opens ImagePreview full-screen viewer', status: 'pending' },
      { id: 'item-5-5', text: 'Product title, price, and condition display correctly', status: 'pending' },
      { id: 'item-5-6', text: 'Product description section displays (CollapsibleSection)', status: 'pending' },
      { id: 'item-5-7', text: 'Product specifications display in CollapsibleCards', status: 'pending' },
      { id: 'item-5-8', text: 'Seller info card displays (name, rating, badges, verified)', status: 'pending' },
      { id: 'item-5-9', text: 'Follow seller button works with optimistic update', status: 'pending' },
      { id: 'item-5-10', text: 'Chat with seller button opens ChatDetails', status: 'pending' },
      { id: 'item-5-11', text: 'Add to wishlist heart icon works with optimistic update', status: 'pending' },
      { id: 'item-5-12', text: 'Remove from wishlist works', status: 'pending' },
      { id: 'item-5-13', text: 'Buy now button navigates to Checkout', status: 'pending' },
      { id: 'item-5-14', text: 'Make offer modal opens with amount and message fields', status: 'pending' },
      { id: 'item-5-15', text: 'Offer validation works (min/max amount)', status: 'pending' },
      { id: 'item-5-16', text: 'Send offer submits successfully', status: 'pending' },
      { id: 'item-5-17', text: 'Share product functionality works (native share sheet)', status: 'pending' },
      { id: 'item-5-18', text: 'Report listing modal opens via ReportListingModal', status: 'pending' },
      { id: 'item-5-19', text: 'Reviews & ratings card displays with breakdown', status: 'pending' },
      { id: 'item-5-20', text: 'Comments section loads with pagination', status: 'pending' },
      { id: 'item-5-21', text: 'Similar products carousel loads at bottom', status: 'pending' },
      { id: 'item-5-22', text: 'Payment method icons display (Visa, MC, GPay, Apple Pay, etc.)', status: 'pending' },
      { id: 'item-5-23', text: 'Shipping info section displays delivery options', status: 'pending' },
      { id: 'item-5-24', text: 'Sticky action bar shows/hides on scroll', status: 'pending' },
      { id: 'item-5-25', text: 'Deep link to product detail works correctly', status: 'pending' },
    ],
  },
  {
    id: 'cl-6',
    title: '🏷️ Auction Detail & Bidding',
    items: [
      { id: 'item-6-1', text: 'Auction detail screen loads for auction-type listings', status: 'pending' },
      { id: 'item-6-2', text: 'CountdownTimer displays and ticks in real-time', status: 'pending' },
      { id: 'item-6-3', text: 'Current highest bid amount displays correctly', status: 'pending' },
      { id: 'item-6-4', text: 'Total bidder count displays', status: 'pending' },
      { id: 'item-6-5', text: 'WebSocket connection establishes (useBidListingWebSocket)', status: 'pending' },
      { id: 'item-6-6', text: 'Real-time bid updates arrive via WebSocket', status: 'pending' },
      { id: 'item-6-7', text: 'Bid placement form opens with min bid auto-calculated', status: 'pending' },
      { id: 'item-6-8', text: 'Bid form validates amount (must be > current bid)', status: 'pending' },
      { id: 'item-6-9', text: 'Bid confirmation modal displays before submitting', status: 'pending' },
      { id: 'item-6-10', text: 'Bid submission succeeds and updates UI', status: 'pending' },
      { id: 'item-6-11', text: 'Bid activity stream shows recent bids with timestamps', status: 'pending' },
      { id: 'item-6-12', text: 'Outbid notification received when someone outbids', status: 'pending' },
      { id: 'item-6-13', text: 'Auction expired state displays correctly', status: 'pending' },
      { id: 'item-6-14', text: 'Bidding history screen loads from profile', status: 'pending' },
      { id: 'item-6-15', text: 'Bidding history details shows bid amount history per item', status: 'pending' },
      { id: 'item-6-16', text: 'Bidding history filters by status (Active, Won, Lost, Outbid)', status: 'pending' },
      { id: 'item-6-17', text: 'BiddingCard component renders correctly in lists', status: 'pending' },
      { id: 'item-6-18', text: 'BiddingMainCard displays large auction card correctly', status: 'pending' },
      { id: 'item-6-19', text: 'CountdownTimerSmall renders in compact card views', status: 'pending' },
    ],
  },
  {
    id: 'cl-7',
    title: '🚗 Car Product Detail',
    items: [
      { id: 'item-7-1', text: 'Car product detail screen loads with vehicle data', status: 'pending' },
      { id: 'item-7-2', text: 'Car images display in carousel', status: 'pending' },
      { id: 'item-7-3', text: 'Vehicle specifications display (make, model, year, mileage)', status: 'pending' },
      { id: 'item-7-4', text: 'Transmission and fuel type display', status: 'pending' },
      { id: 'item-7-5', text: 'Vehicle features list displays', status: 'pending' },
      { id: 'item-7-6', text: 'Vehicle condition/inspection badge displays', status: 'pending' },
      { id: 'item-7-7', text: 'Buy now button works for vehicles', status: 'pending' },
      { id: 'item-7-8', text: 'Make offer button works for vehicles', status: 'pending' },
      { id: 'item-7-9', text: 'Seller info card displays for vehicle seller', status: 'pending' },
      { id: 'item-7-10', text: 'Similar vehicles carousel loads', status: 'pending' },
      { id: 'item-7-11', text: 'VehiclesCard component renders correctly in lists', status: 'pending' },
    ],
  },
  {
    id: 'cl-8',
    title: '🏘️ Real Estate Detail',
    items: [
      { id: 'item-8-1', text: 'Real estate detail screen loads with property data', status: 'pending' },
      { id: 'item-8-2', text: 'Property images display in carousel', status: 'pending' },
      { id: 'item-8-3', text: 'Property specs display (rooms, bathrooms, area/sqm)', status: 'pending' },
      { id: 'item-8-4', text: 'Amenities list displays in collapsible section', status: 'pending' },
      { id: 'item-8-5', text: 'Floor plan images display if available', status: 'pending' },
      { id: 'item-8-6', text: 'Location map integration displays property location', status: 'pending' },
      { id: 'item-8-7', text: 'Virtual tour link/feature works if available', status: 'pending' },
      { id: 'item-8-8', text: 'Property condition ratings display', status: 'pending' },
      { id: 'item-8-9', text: 'Buy now / Make offer works for real estate', status: 'pending' },
      { id: 'item-8-10', text: 'Seller info card displays for property seller', status: 'pending' },
      { id: 'item-8-11', text: 'Similar properties carousel loads', status: 'pending' },
      { id: 'item-8-12', text: 'RealstatesCard component renders correctly in lists', status: 'pending' },
    ],
  },
  {
    id: 'cl-9',
    title: '📝 Add Listing (Standard Product)',
    items: [
      { id: 'item-9-1', text: 'AddListing screen loads from Sell button modal (Normal option)', status: 'pending' },
      { id: 'item-9-2', text: 'AddListingDrawer opens and displays step navigation', status: 'pending' },
      { id: 'item-9-3', text: 'Drawer shows current step highlighted', status: 'pending' },
      { id: 'item-9-4', text: 'Step selection from drawer navigates correctly', status: 'pending' },
      { id: 'item-9-5', text: 'LoadingScreen displays during listing operations', status: 'pending' },
      { id: 'item-9-6', text: 'Step 1 - StartListing: Begin listing wizard loads', status: 'pending' },
      { id: 'item-9-7', text: 'Step 1 - DescribeItem: Title and description form works', status: 'pending' },
      { id: 'item-9-8', text: 'Step 1 - DescribeItem: Form validation (title required, min length)', status: 'pending' },
      { id: 'item-9-9', text: 'Step 1 - AiUpload: AI-powered image suggestion works', status: 'pending' },
      { id: 'item-9-10', text: 'Step 1 - AboutProduct: Category selection via CustomCategoryModal', status: 'pending' },
      { id: 'item-9-11', text: 'Step 1 - AboutProduct: Subcategory selection via CustomSubcategoryModal', status: 'pending' },
      { id: 'item-9-12', text: 'Step 1 - AboutProduct: Specification selection via CustomSpecificationModal', status: 'pending' },
      { id: 'item-9-13', text: 'Step 1 - DescribeCondition: Product condition selection works', status: 'pending' },
      { id: 'item-9-14', text: 'Step 1 - AdditionalInformation: Extra specs form works', status: 'pending' },
      { id: 'item-9-15', text: 'Step 2 - MediaUpload: Image selection from gallery works', status: 'pending' },
      { id: 'item-9-16', text: 'Step 2 - MediaUpload: Take photo from camera works', status: 'pending' },
      { id: 'item-9-17', text: 'Step 2 - MediaUpload: Image compression works', status: 'pending' },
      { id: 'item-9-18', text: 'Step 2 - MediaUpload: Multiple image upload works', status: 'pending' },
      { id: 'item-9-19', text: 'Step 2 - MediaPreview: Preview uploaded images', status: 'pending' },
      { id: 'item-9-20', text: 'Step 2 - MediaUpload: Delete uploaded image works', status: 'pending' },
      { id: 'item-9-21', text: 'Step 2 - ProductDescription: Long-form description editor works', status: 'pending' },
      { id: 'item-9-22', text: 'Step 2 - Standout: Feature badges and seller story work', status: 'pending' },
      { id: 'item-9-23', text: 'Step 3 - ListingType: Fixed price vs Auction selection works', status: 'pending' },
      { id: 'item-9-24', text: 'Step 3 - SetYourPrice: Price input and validation works', status: 'pending' },
      { id: 'item-9-25', text: 'Step 3 - ChooseShippingType: Shipping method selection works', status: 'pending' },
      { id: 'item-9-26', text: 'Step 3 - ShippingEstimatedCalculation: Cost calculation works', status: 'pending' },
      { id: 'item-9-27', text: 'Step 3 - NewAddress: Seller address form with map works', status: 'pending' },
      { id: 'item-9-28', text: 'Step 3 - ReturnPolicySetting: Return policy config works', status: 'pending' },
      { id: 'item-9-29', text: 'Step 3 - EditSellerProfile: Seller profile completion works', status: 'pending' },
      { id: 'item-9-30', text: 'Step 3 - VerifyAccount: Account verification check works', status: 'pending' },
      { id: 'item-9-31', text: 'Step 3 - PublishIntro: Pre-publish info screen displays', status: 'pending' },
      { id: 'item-9-32', text: 'Step 3 - ReviewListing: Final listing review displays all data', status: 'pending' },
      { id: 'item-9-33', text: 'Step 3 - ConfirmListing: Confirm and publish works', status: 'pending' },
      { id: 'item-9-34', text: 'Step 4 - TaxDetailsStep: VAT/tax details form works', status: 'pending' },
      { id: 'item-9-35', text: 'Navigation between all steps works (next/back)', status: 'pending' },
      { id: 'item-9-36', text: 'Draft saving preserves incomplete listing data', status: 'pending' },
      { id: 'item-9-37', text: 'Listing confirmation screen displays after publish', status: 'pending' },
    ],
  },
  {
    id: 'cl-10',
    title: '🚗 Car Listing Flow',
    items: [
      { id: 'item-10-1', text: 'Car listing screen loads from Sell button modal (Vehicles option)', status: 'pending' },
      { id: 'item-10-2', text: 'CarListingDrawer opens with step navigation', status: 'pending' },
      { id: 'item-10-3', text: 'Car LoadingScreen displays during operations', status: 'pending' },
      { id: 'item-10-4', text: 'StartListing: Begin car listing wizard', status: 'pending' },
      { id: 'item-10-5', text: 'AboutProduct: Make/Model/Year dropdown selection works', status: 'pending' },
      { id: 'item-10-6', text: 'AboutProduct: Mileage input works', status: 'pending' },
      { id: 'item-10-7', text: 'AboutProduct: Transmission type selection works', status: 'pending' },
      { id: 'item-10-8', text: 'AboutProduct: Fuel type selection works', status: 'pending' },
      { id: 'item-10-9', text: 'AboutProduct: Color selection works', status: 'pending' },
      { id: 'item-10-10', text: 'DescribeCondition: Vehicle condition assessment works', status: 'pending' },
      { id: 'item-10-11', text: 'AdditionalInformation: Vehicle-specific specs form works', status: 'pending' },
      { id: 'item-10-12', text: 'AiUpload: AI upload for vehicles works', status: 'pending' },
      { id: 'item-10-13', text: 'MediaUpload: Vehicle images upload works', status: 'pending' },
      { id: 'item-10-14', text: 'MediaPreview: Vehicle images preview works', status: 'pending' },
      { id: 'item-10-15', text: 'ProductDescription: Vehicle description editor works', status: 'pending' },
      { id: 'item-10-16', text: 'Standout: Vehicle standout features work', status: 'pending' },
      { id: 'item-10-17', text: 'SetYourPrice: Vehicle pricing works', status: 'pending' },
      { id: 'item-10-18', text: 'ListingType: Fixed price vs Auction for vehicles', status: 'pending' },
      { id: 'item-10-19', text: 'ChooseShippingType: Vehicle shipping options work', status: 'pending' },
      { id: 'item-10-20', text: 'ReturnPolicySetting: Vehicle return policy works', status: 'pending' },
      { id: 'item-10-21', text: 'NewAddress: Vehicle seller address works', status: 'pending' },
      { id: 'item-10-22', text: 'VerifyAccount: Account verification for vehicle seller', status: 'pending' },
      { id: 'item-10-23', text: 'ReviewListing: Vehicle listing review displays all specs', status: 'pending' },
      { id: 'item-10-24', text: 'ConfirmListing: Vehicle listing publish works', status: 'pending' },
      { id: 'item-10-25', text: 'Car listing confirmation screen displays', status: 'pending' },
    ],
  },
  {
    id: 'cl-11',
    title: '🏠 Real Estate Listing Flow (V3)',
    items: [
      { id: 'item-11-1', text: 'Real estate listing loads from Sell button modal (Real Estate option)', status: 'pending' },
      { id: 'item-11-2', text: 'RealStateListingDrawer opens with step navigation', status: 'pending' },
      { id: 'item-11-3', text: 'V3 Step 1: Property type selection works', status: 'pending' },
      { id: 'item-11-4', text: 'V3 Step 1: Location input/selection works', status: 'pending' },
      { id: 'item-11-5', text: 'V3 Step 2: Rooms count input works', status: 'pending' },
      { id: 'item-11-6', text: 'V3 Step 2: Bathrooms count input works', status: 'pending' },
      { id: 'item-11-7', text: 'V3 Step 2: Area/size input with unit selection (sqft/sqm) works', status: 'pending' },
      { id: 'item-11-8', text: 'V3 Step 3: Amenities multi-select chips work (parking, pool, garden, etc.)', status: 'pending' },
      { id: 'item-11-9', text: 'V3 Step 4: Property images upload works', status: 'pending' },
      { id: 'item-11-10', text: 'V3 Step 4: Floor plan image upload works', status: 'pending' },
      { id: 'item-11-11', text: 'V3 Step 4: Virtual tour upload/link works', status: 'pending' },
      { id: 'item-11-12', text: 'V3 Step 5: Property pricing input works', status: 'pending' },
      { id: 'item-11-13', text: 'V3 Step 5: Currency selection works', status: 'pending' },
      { id: 'item-11-14', text: 'V3 Step 6: Property description text editor works', status: 'pending' },
      { id: 'item-11-15', text: 'V3 Step 7: Review displays all property data correctly', status: 'pending' },
      { id: 'item-11-16', text: 'V3 Step 7: Publish property listing works', status: 'pending' },
      { id: 'item-11-17', text: 'Navigation between all 7 steps works (next/back)', status: 'pending' },
      { id: 'item-11-18', text: 'Enhanced step navigation drawer highlights current step', status: 'pending' },
      { id: 'item-11-19', text: 'Map integration for location selection works', status: 'pending' },
      { id: 'item-11-20', text: 'Real estate listing confirmation displays', status: 'pending' },
    ],
  },
  {
    id: 'cl-12',
    title: '🏪 Seller Dashboard & Listings',
    items: [
      { id: 'item-12-1', text: 'Seller dashboard screen loads with analytics', status: 'pending' },
      { id: 'item-12-2', text: 'Revenue/sales overview chart (SalesReportChart) renders', status: 'pending' },
      { id: 'item-12-3', text: 'Stats cards display (total sales, active items, orders)', status: 'pending' },
      { id: 'item-12-4', text: 'Customer growth chart (CustomerGrowthChart) renders', status: 'pending' },
      { id: 'item-12-5', text: 'Overview chart (OverViewChart) renders', status: 'pending' },
      { id: 'item-12-6', text: 'Recent transactions list displays', status: 'pending' },
      { id: 'item-12-7', text: 'Dashboard pull-to-refresh works', status: 'pending' },
      { id: 'item-12-8', text: 'Mode switching (SwitchScreensButton) buyer/seller works', status: 'pending' },
      { id: 'item-12-9', text: 'Seller listings screen loads from tab', status: 'pending' },
      { id: 'item-12-10', text: 'Active listings display with count badge', status: 'pending' },
      { id: 'item-12-11', text: 'Draft listings display', status: 'pending' },
      { id: 'item-12-12', text: 'Sold listings display', status: 'pending' },
      { id: 'item-12-13', text: 'Archived/Deactivated listings display', status: 'pending' },
      { id: 'item-12-14', text: 'SellerListingToggle status filter tabs work', status: 'pending' },
      { id: 'item-12-15', text: 'List/Grid view toggle works', status: 'pending' },
      { id: 'item-12-16', text: 'Seller listing details screen loads', status: 'pending' },
      { id: 'item-12-17', text: 'Listing analytics (views, clicks, saves) display', status: 'pending' },
      { id: 'item-12-18', text: 'Edit listing button navigates to EditSellerListingDetails', status: 'pending' },
      { id: 'item-12-19', text: 'OptionsModal quick actions (Edit, Deactivate, Archive, Mark Sold)', status: 'pending' },
      { id: 'item-12-20', text: 'DeactivateModal confirmation works', status: 'pending' },
      { id: 'item-12-21', text: 'ArchiveModal confirmation works', status: 'pending' },
      { id: 'item-12-22', text: 'MarkAsSoldModal confirmation works', status: 'pending' },
      { id: 'item-12-23', text: 'Seller vehicle listing details screen loads', status: 'pending' },
      { id: 'item-12-24', text: 'Seller real estate listing details screen loads', status: 'pending' },
      { id: 'item-12-25', text: 'Edit seller listing details saves changes', status: 'pending' },
    ],
  },
  {
    id: 'cl-13',
    title: '💰 Offers Management',
    items: [
      { id: 'item-13-1', text: 'Offers screen loads with sent/received tabs', status: 'pending' },
      { id: 'item-13-2', text: 'Sent offers list displays with OfferCards', status: 'pending' },
      { id: 'item-13-3', text: 'Received offers list displays', status: 'pending' },
      { id: 'item-13-4', text: 'Offer status badges display (Pending, Accepted, Rejected, Expired)', status: 'pending' },
      { id: 'item-13-5', text: 'Offer details screen loads with full offer info', status: 'pending' },
      { id: 'item-13-6', text: 'Accept offer works from OfferActionModal', status: 'pending' },
      { id: 'item-13-7', text: 'Reject offer works', status: 'pending' },
      { id: 'item-13-8', text: 'Counter-offer submission works', status: 'pending' },
      { id: 'item-13-9', text: 'Withdraw sent offer works', status: 'pending' },
      { id: 'item-13-10', text: 'Offer expiration displays countdown', status: 'pending' },
      { id: 'item-13-11', text: 'Offer notifications received (push)', status: 'pending' },
      { id: 'item-13-12', text: 'RecentOffersToggle displays recent activity', status: 'pending' },
      { id: 'item-13-13', text: 'Offer sort and filter work', status: 'pending' },
    ],
  },
  {
    id: 'cl-14',
    title: '🛒 Checkout & Payment',
    items: [
      { id: 'item-14-1', text: 'Checkout screen loads with order summary', status: 'pending' },
      { id: 'item-14-2', text: 'Order items display correctly with images and prices', status: 'pending' },
      { id: 'item-14-3', text: 'Delivery address selection from saved addresses works', status: 'pending' },
      { id: 'item-14-4', text: 'Add new address from checkout navigates to AddAddress', status: 'pending' },
      { id: 'item-14-5', text: 'Delivery type selection works (truck, pickup, drop-off)', status: 'pending' },
      { id: 'item-14-6', text: 'Shipping carrier selection works', status: 'pending' },
      { id: 'item-14-7', text: 'Shipping cost calculates and displays', status: 'pending' },
      { id: 'item-14-8', text: 'Delivery instructions input works', status: 'pending' },
      { id: 'item-14-9', text: 'Contact preference selection works (email, phone)', status: 'pending' },
      { id: 'item-14-10', text: 'Payment method selection works', status: 'pending' },
      { id: 'item-14-11', text: 'Saved payment cards display and are selectable', status: 'pending' },
      { id: 'item-14-12', text: 'Add new payment card option works', status: 'pending' },
      { id: 'item-14-13', text: 'Coupon/promo code input and apply works', status: 'pending' },
      { id: 'item-14-14', text: 'Price breakdown displays (subtotal, shipping, tax, total)', status: 'pending' },
      { id: 'item-14-15', text: 'Tax calculation displays correctly', status: 'pending' },
      { id: 'item-14-16', text: 'Total price calculates correctly with all fees', status: 'pending' },
      { id: 'item-14-17', text: 'Submit order button triggers payment flow', status: 'pending' },
      { id: 'item-14-18', text: 'PaymentWebView loads payment gateway', status: 'pending' },
      { id: 'item-14-19', text: 'Google Pay payment works', status: 'pending' },
      { id: 'item-14-20', text: 'Apple Pay payment works', status: 'pending' },
      { id: 'item-14-21', text: 'Card payment (Visa/Mastercard) processing works', status: 'pending' },
      { id: 'item-14-22', text: 'Tamara (buy now pay later) integration works', status: 'pending' },
      { id: 'item-14-23', text: 'Stc Pay integration works', status: 'pending' },
      { id: 'item-14-24', text: 'Csmada Pay integration works', status: 'pending' },
      { id: 'item-14-25', text: 'Payment success handling navigates to confirmation', status: 'pending' },
      { id: 'item-14-26', text: 'Payment failure shows error and allows retry', status: 'pending' },
      { id: 'item-14-27', text: 'Payment cancellation returns to checkout', status: 'pending' },
      { id: 'item-14-28', text: 'OrderSubmission confirmation screen displays order number', status: 'pending' },
      { id: 'item-14-29', text: 'Navigation after order goes to BuyerOrders', status: 'pending' },
    ],
  },
  {
    id: 'cl-15',
    title: '💳 Installments',
    items: [
      { id: 'item-15-1', text: 'Installments screen loads from product or checkout', status: 'pending' },
      { id: 'item-15-2', text: 'Available installment plans display', status: 'pending' },
      { id: 'item-15-3', text: 'Monthly payment breakdown calculates correctly', status: 'pending' },
      { id: 'item-15-4', text: 'Installment plan selection works', status: 'pending' },
      { id: 'item-15-5', text: 'Eligibility check displays result', status: 'pending' },
      { id: 'item-15-6', text: 'Selected plan integrates with checkout flow', status: 'pending' },
    ],
  },
  {
    id: 'cl-16',
    title: '📋 Order Management (Buyer)',
    items: [
      { id: 'item-16-1', text: 'Buyer orders screen loads from profile/tab', status: 'pending' },
      { id: 'item-16-2', text: 'Order list displays with OrderCards', status: 'pending' },
      { id: 'item-16-3', text: 'Order status badges display (Processing, Shipped, Delivered, Cancelled)', status: 'pending' },
      { id: 'item-16-4', text: 'Order status filter tabs work', status: 'pending' },
      { id: 'item-16-5', text: 'Order details screen loads with full info', status: 'pending' },
      { id: 'item-16-6', text: 'Order items display with images and quantities', status: 'pending' },
      { id: 'item-16-7', text: 'Order history screen loads past orders', status: 'pending' },
      { id: 'item-16-8', text: 'Track order screen loads with shipment tracking', status: 'pending' },
      { id: 'item-16-9', text: 'Tracking status timeline updates display', status: 'pending' },
      { id: 'item-16-10', text: 'Delivery map shows shipment location', status: 'pending' },
      { id: 'item-16-11', text: 'Reorder button works from past orders', status: 'pending' },
    ],
  },
  {
    id: 'cl-17',
    title: '📋 Order Management (Seller)',
    items: [
      { id: 'item-17-1', text: 'Seller orders screen loads from seller tab', status: 'pending' },
      { id: 'item-17-2', text: 'Seller order list displays with OrderManagementCards', status: 'pending' },
      { id: 'item-17-3', text: 'Order status filter works', status: 'pending' },
      { id: 'item-17-4', text: 'Seller order details screen loads', status: 'pending' },
      { id: 'item-17-5', text: 'Buyer info, items, amount display correctly', status: 'pending' },
      { id: 'item-17-6', text: 'Confirm order action works', status: 'pending' },
      { id: 'item-17-7', text: 'Print shipping label action works', status: 'pending' },
      { id: 'item-17-8', text: 'Track shipment action works', status: 'pending' },
      { id: 'item-17-9', text: 'Cancel order action works with confirmation', status: 'pending' },
      { id: 'item-17-10', text: 'Order fulfillment workflow completes', status: 'pending' },
    ],
  },
  {
    id: 'cl-18',
    title: '🔄 Return Orders',
    items: [
      { id: 'item-18-1', text: 'Buyer return order instructions screen loads', status: 'pending' },
      { id: 'item-18-2', text: 'Return request creation form works', status: 'pending' },
      { id: 'item-18-3', text: 'Buyer return order details display with tracking', status: 'pending' },
      { id: 'item-18-4', text: 'Buyer review request (rate return experience) works', status: 'pending' },
      { id: 'item-18-5', text: 'Buyer dispute return order form works', status: 'pending' },
      { id: 'item-18-6', text: 'Return status updates display correctly', status: 'pending' },
      { id: 'item-18-7', text: 'Seller return order screen loads', status: 'pending' },
      { id: 'item-18-8', text: 'Seller return order details load with item info', status: 'pending' },
      { id: 'item-18-9', text: 'Seller approve return works', status: 'pending' },
      { id: 'item-18-10', text: 'Seller reject return with reason works', status: 'pending' },
      { id: 'item-18-11', text: 'Return order invoice (SellerReturnOrderDetailsInvoice) displays', status: 'pending' },
      { id: 'item-18-12', text: 'Return tracking updates work', status: 'pending' },
    ],
  },
  {
    id: 'cl-19',
    title: '👤 Profile Management',
    items: [
      { id: 'item-19-1', text: 'Profile screen loads from bottom tab', status: 'pending' },
      { id: 'item-19-2', text: 'ProfileHeaderNew displays avatar, name, ratings, stats', status: 'pending' },
      { id: 'item-19-3', text: 'Profile tabs (Overview, Listings, Reviews, Orders) work', status: 'pending' },
      { id: 'item-19-4', text: 'Followers/following counts display correctly', status: 'pending' },
      { id: 'item-19-5', text: 'Profile info screen loads with personal information', status: 'pending' },
      { id: 'item-19-6', text: 'Edit profile screen loads with current data', status: 'pending' },
      { id: 'item-19-7', text: 'Profile image upload works (camera/gallery with crop)', status: 'pending' },
      { id: 'item-19-8', text: 'Profile update (name, email, phone, bio) saves correctly', status: 'pending' },
      { id: 'item-19-9', text: 'Profile validation errors display', status: 'pending' },
      { id: 'item-19-10', text: 'Edit seller profile main screen loads', status: 'pending' },
      { id: 'item-19-11', text: 'Seller profile (store name, description, policies) saves', status: 'pending' },
      { id: 'item-19-12', text: 'Seller personal info screen loads', status: 'pending' },
      { id: 'item-19-13', text: 'Business verification (KYC) flow works', status: 'pending' },
      { id: 'item-19-14', text: 'IdentityVerificationBanner shows when not verified', status: 'pending' },
      { id: 'item-19-15', text: 'Change password works', status: 'pending' },
      { id: 'item-19-16', text: 'ProfileQrModal displays QR code for sharing', status: 'pending' },
      { id: 'item-19-17', text: 'LogoutModal confirmation and logout flow works', status: 'pending' },
    ],
  },
  {
    id: 'cl-20',
    title: '📍 Addresses & Payment Cards',
    items: [
      { id: 'item-20-1', text: 'Saved addresses screen loads with AddressCards', status: 'pending' },
      { id: 'item-20-2', text: 'Add new address screen loads with map', status: 'pending' },
      { id: 'item-20-3', text: 'Address form validates all fields', status: 'pending' },
      { id: 'item-20-4', text: 'Map location picker works (drag pin)', status: 'pending' },
      { id: 'item-20-5', text: 'Address geocoding resolves correctly', status: 'pending' },
      { id: 'item-20-6', text: 'Edit existing address works', status: 'pending' },
      { id: 'item-20-7', text: 'Delete address works with confirmation', status: 'pending' },
      { id: 'item-20-8', text: 'Set default address works', status: 'pending' },
      { id: 'item-20-9', text: 'Payment cards screen loads with saved cards', status: 'pending' },
      { id: 'item-20-10', text: 'Add new payment card works', status: 'pending' },
      { id: 'item-20-11', text: 'Delete payment card works', status: 'pending' },
      { id: 'item-20-12', text: 'Set default payment card works', status: 'pending' },
      { id: 'item-20-13', text: 'Payment tokens save correctly for future use', status: 'pending' },
    ],
  },
  {
    id: 'cl-21',
    title: '👥 Public Profile & Social',
    items: [
      { id: 'item-21-1', text: 'Public profile screen loads for other users', status: 'pending' },
      { id: 'item-21-2', text: 'Public profile info displays (name, avatar, ratings)', status: 'pending' },
      { id: 'item-21-3', text: 'PublicProfileCard renders correctly', status: 'pending' },
      { id: 'item-21-4', text: 'Seller listings display on public profile', status: 'pending' },
      { id: 'item-21-5', text: 'Follow/unfollow from public profile works with optimistic update', status: 'pending' },
      { id: 'item-21-6', text: 'Followers screen loads with follower list', status: 'pending' },
      { id: 'item-21-7', text: 'Following list displays', status: 'pending' },
      { id: 'item-21-8', text: 'Remove follower works', status: 'pending' },
      { id: 'item-21-9', text: 'Blocked users screen loads', status: 'pending' },
      { id: 'item-21-10', text: 'Block user works', status: 'pending' },
      { id: 'item-21-11', text: 'Unblock user works', status: 'pending' },
    ],
  },
  {
    id: 'cl-22',
    title: '💬 Messaging & Chat',
    items: [
      { id: 'item-22-1', text: 'Messages screen loads with chat list', status: 'pending' },
      { id: 'item-22-2', text: 'Chat tabs work (Active, Archive, Groups)', status: 'pending' },
      { id: 'item-22-3', text: 'Unread message badge count displays', status: 'pending' },
      { id: 'item-22-4', text: 'Chat search/filter works', status: 'pending' },
      { id: 'item-22-5', text: 'Last message preview shows in chat list', status: 'pending' },
      { id: 'item-22-6', text: 'Online status indicator displays', status: 'pending' },
      { id: 'item-22-7', text: 'Swipe to archive/delete chat works', status: 'pending' },
      { id: 'item-22-8', text: 'Chat details screen loads with message history', status: 'pending' },
      { id: 'item-22-9', text: 'Send text message works via WebSocket (useChatWebSocket)', status: 'pending' },
      { id: 'item-22-10', text: 'Receive message works in real-time', status: 'pending' },
      { id: 'item-22-11', text: 'Send image in chat works', status: 'pending' },
      { id: 'item-22-12', text: 'Typing indicator displays', status: 'pending' },
      { id: 'item-22-13', text: 'Delivery/read receipts display', status: 'pending' },
      { id: 'item-22-14', text: 'Message timestamps display correctly', status: 'pending' },
      { id: 'item-22-15', text: 'Chat header shows user info and online status', status: 'pending' },
      { id: 'item-22-16', text: 'Message notification tap opens correct chat', status: 'pending' },
    ],
  },
  {
    id: 'cl-23',
    title: '❤️ Wishlist & Browser History',
    items: [
      { id: 'item-23-1', text: 'Wishlist screen loads with saved products', status: 'pending' },
      { id: 'item-23-2', text: 'Wishlist items display in grid/list', status: 'pending' },
      { id: 'item-23-3', text: 'Add to wishlist from product detail works', status: 'pending' },
      { id: 'item-23-4', text: 'Add to wishlist from product card works', status: 'pending' },
      { id: 'item-23-5', text: 'Remove from wishlist works', status: 'pending' },
      { id: 'item-23-6', text: 'Wishlist optimistic updates (instant UI feedback)', status: 'pending' },
      { id: 'item-23-7', text: 'Empty wishlist state displays', status: 'pending' },
      { id: 'item-23-8', text: 'Navigate to product from wishlist works', status: 'pending' },
      { id: 'item-23-9', text: 'Wishlist persists across app restarts', status: 'pending' },
      { id: 'item-23-10', text: 'Browser history screen loads', status: 'pending' },
      { id: 'item-23-11', text: 'History items display with product info', status: 'pending' },
      { id: 'item-23-12', text: 'Clear individual history item works', status: 'pending' },
      { id: 'item-23-13', text: 'Clear all history works', status: 'pending' },
      { id: 'item-23-14', text: 'Navigate from history to product detail works', status: 'pending' },
    ],
  },
  {
    id: 'cl-24',
    title: '💼 Seller Wallet',
    items: [
      { id: 'item-24-1', text: 'Seller wallet screen loads', status: 'pending' },
      { id: 'item-24-2', text: 'Wallet balance displays correctly', status: 'pending' },
      { id: 'item-24-3', text: 'Transaction history list displays', status: 'pending' },
      { id: 'item-24-4', text: 'TransactionDetailsModal shows transaction info', status: 'pending' },
      { id: 'item-24-5', text: 'Wallet transactions filter/sort works', status: 'pending' },
      { id: 'item-24-6', text: 'WithdrawalModal opens for withdrawal request', status: 'pending' },
      { id: 'item-24-7', text: 'Withdrawal submission works', status: 'pending' },
      { id: 'item-24-8', text: 'WithdrawalDetailsModal shows withdrawal history', status: 'pending' },
    ],
  },
  {
    id: 'cl-25',
    title: '🔔 Notifications & Push',
    items: [
      { id: 'item-25-1', text: 'Notification screen loads with notification list', status: 'pending' },
      { id: 'item-25-2', text: 'Notification types display correctly (order, bid, message, system)', status: 'pending' },
      { id: 'item-25-3', text: 'Notification tap navigates to relevant screen', status: 'pending' },
      { id: 'item-25-4', text: 'Mark notification as read works', status: 'pending' },
      { id: 'item-25-5', text: 'Clear/delete notifications works', status: 'pending' },
      { id: 'item-25-6', text: 'Push notifications received via FCM', status: 'pending' },
      { id: 'item-25-7', text: 'Push notifications received via OneSignal', status: 'pending' },
      { id: 'item-25-8', text: 'Local notifications via Notifee work', status: 'pending' },
      { id: 'item-25-9', text: 'Push notification tap opens correct screen (deep linking)', status: 'pending' },
      { id: 'item-25-10', text: 'Notification badge count updates on bottom tab', status: 'pending' },
      { id: 'item-25-11', text: 'Cold start notification navigation works', status: 'pending' },
    ],
  },
  {
    id: 'cl-26',
    title: '📸 Camera & Media',
    items: [
      { id: 'item-26-1', text: 'Camera screen opens via VisionCamera', status: 'pending' },
      { id: 'item-26-2', text: 'Take photo works', status: 'pending' },
      { id: 'item-26-3', text: 'CustomCamera screen works', status: 'pending' },
      { id: 'item-26-4', text: 'Select from gallery via ImageCropPicker works', status: 'pending' },
      { id: 'item-26-5', text: 'Image cropping tool works', status: 'pending' },
      { id: 'item-26-6', text: 'Multiple image selection works', status: 'pending' },
      { id: 'item-26-7', text: 'Image compression via Compressor works', status: 'pending' },
      { id: 'item-26-8', text: 'Image preview screen loads with pinch-to-zoom', status: 'pending' },
      { id: 'item-26-9', text: 'ImageUploadGrid displays uploaded images correctly', status: 'pending' },
      { id: 'item-26-10', text: 'Document picker works for file attachments', status: 'pending' },
    ],
  },
  {
    id: 'cl-27',
    title: '🗺️ Navigation & Tab Bar',
    items: [
      { id: 'item-27-1', text: 'Home tab works and loads HomeScreen', status: 'pending' },
      { id: 'item-27-2', text: 'Shop/Categories tab works and loads CategoryProducts', status: 'pending' },
      { id: 'item-27-3', text: 'Center Sell button opens listing type modal', status: 'pending' },
      { id: 'item-27-4', text: 'Listing modal shows 3 options: Normal, Vehicles, Real Estate', status: 'pending' },
      { id: 'item-27-5', text: 'Normal product option navigates to AddListing', status: 'pending' },
      { id: 'item-27-6', text: 'Vehicles option navigates to CarListing', status: 'pending' },
      { id: 'item-27-7', text: 'Real estate option navigates to RealstateAddListing', status: 'pending' },
      { id: 'item-27-8', text: 'Modal closes after selection', status: 'pending' },
      { id: 'item-27-9', text: 'My Listings tab works (shows active listings badge)', status: 'pending' },
      { id: 'item-27-10', text: 'Profile tab works and loads ProfileScreenNavigators', status: 'pending' },
      { id: 'item-27-11', text: 'Tab indicator bar animates on switch', status: 'pending' },
      { id: 'item-27-12', text: 'Tab switching is smooth with reanimated animation', status: 'pending' },
      { id: 'item-27-13', text: 'Login check before seller features (unauthenticated redirect)', status: 'pending' },
      { id: 'item-27-14', text: 'Mode switching (buyer/seller) updates tab content', status: 'pending' },
      { id: 'item-27-15', text: 'Drawer navigator swaps correctly (Home/AddListing/CarListing/RealState)', status: 'pending' },
      { id: 'item-27-16', text: 'Back button/gesture works across all screens', status: 'pending' },
      { id: 'item-27-17', text: 'Deep linking navigates to correct screen', status: 'pending' },
      { id: 'item-27-18', text: 'Navigation transitions are smooth (no flicker)', status: 'pending' },
      { id: 'item-27-19', text: 'No navigation loops or duplicate screens in stack', status: 'pending' },
      { id: 'item-27-20', text: 'Screen params pass correctly between screens', status: 'pending' },
    ],
  },
  {
    id: 'cl-28',
    title: '🎓 Tour & Onboarding Overlay',
    items: [
      { id: 'item-28-1', text: 'TourOverlay displays for first-time users', status: 'pending' },
      { id: 'item-28-2', text: 'Tour Step 2: Sell button tutorial highlights correctly', status: 'pending' },
      { id: 'item-28-3', text: 'Tour Step 3: My Listings tutorial highlights correctly', status: 'pending' },
      { id: 'item-28-4', text: 'Tour Step 4: Account/Profile tutorial highlights correctly', status: 'pending' },
      { id: 'item-28-5', text: 'Tour step-by-step navigation works (next/previous)', status: 'pending' },
      { id: 'item-28-6', text: 'Skip tour option works', status: 'pending' },
      { id: 'item-28-7', text: 'Tour completion state persists (does not show again)', status: 'pending' },
    ],
  },
  {
    id: 'cl-29',
    title: '🆘 Help & Support',
    items: [
      { id: 'item-29-1', text: 'HelpSupportModal opens from profile/settings', status: 'pending' },
      { id: 'item-29-2', text: 'FAQ items display and are expandable', status: 'pending' },
      { id: 'item-29-3', text: 'Contact support option works', status: 'pending' },
      { id: 'item-29-4', text: 'Content safety modal displays policy info', status: 'pending' },
      { id: 'item-29-5', text: 'RatingModal prompts user to rate app (rateApp utility)', status: 'pending' },
      { id: 'item-29-6', text: 'Shipping services configuration screen loads', status: 'pending' },
      { id: 'item-29-7', text: 'Shipping carrier setup works', status: 'pending' },
    ],
  },
  {
    id: 'cl-30',
    title: '🌐 Internationalization & RTL',
    items: [
      { id: 'item-30-1', text: 'Language switching works via TranslationContext', status: 'pending' },
      { id: 'item-30-2', text: 'Arabic (RTL) layout displays correctly', status: 'pending' },
      { id: 'item-30-3', text: 'English (LTR) layout displays correctly', status: 'pending' },
      { id: 'item-30-4', text: 'Text alignment flips correctly in RTL (rtlUtils)', status: 'pending' },
      { id: 'item-30-5', text: 'Icons/arrows flip correctly in RTL', status: 'pending' },
      { id: 'item-30-6', text: 'Navigation drawer direction correct in RTL', status: 'pending' },
      { id: 'item-30-7', text: 'All UI strings use t() translation function', status: 'pending' },
      { id: 'item-30-8', text: 'No hardcoded strings visible in UI', status: 'pending' },
      { id: 'item-30-9', text: 'Date/time formats respect locale (dateFormatter)', status: 'pending' },
      { id: 'item-30-10', text: 'Number formats respect locale', status: 'pending' },
      { id: 'item-30-11', text: 'Currency displays correctly as SAR (CurrencyUtils)', status: 'pending' },
      { id: 'item-30-12', text: 'Language preference persists in AsyncStorage', status: 'pending' },
    ],
  },
  {
    id: 'cl-31',
    title: '🎨 UI/UX & Theming',
    items: [
      { id: 'item-31-1', text: 'Light theme displays correctly (withTheme HOC)', status: 'pending' },
      { id: 'item-31-2', text: 'Dark theme displays correctly', status: 'pending' },
      { id: 'item-31-3', text: 'Theme switching works and persists', status: 'pending' },
      { id: 'item-31-4', text: 'Theme colors are consistent across all screens', status: 'pending' },
      { id: 'item-31-5', text: 'Fonts load correctly (FontFamily: REGULAR, MEDIUM, BOLD, SEMI_BOLD)', status: 'pending' },
      { id: 'item-31-6', text: 'Font sizes scale correctly (FontSize enums)', status: 'pending' },
      { id: 'item-31-7', text: 'Safe area insets work (notches, dynamic island)', status: 'pending' },
      { id: 'item-31-8', text: 'Responsive layout works on different screen sizes (ResponsiveUtils)', status: 'pending' },
      { id: 'item-31-9', text: 'Tablet layout works correctly', status: 'pending' },
      { id: 'item-31-10', text: 'Phone layout works correctly', status: 'pending' },
      { id: 'item-31-11', text: 'Images scale correctly with FastImage', status: 'pending' },
      { id: 'item-31-12', text: 'Lottie animations render (lottie-react-native)', status: 'pending' },
      { id: 'item-31-13', text: 'Moti animations work smoothly', status: 'pending' },
      { id: 'item-31-14', text: 'Reanimated animations work (tab bar, sticky bar, carousels)', status: 'pending' },
      { id: 'item-31-15', text: 'Bottom sheets (Gorhom) open/close/snap correctly', status: 'pending' },
      { id: 'item-31-16', text: 'Modals (react-native-modal) open/close correctly', status: 'pending' },
      { id: 'item-31-17', text: 'Skeleton loading screens display during data fetch', status: 'pending' },
      { id: 'item-31-18', text: 'No style overflows or layout breaking', status: 'pending' },
    ],
  },
  {
    id: 'cl-32',
    title: '🔧 RTK Query & State Management',
    items: [
      { id: 'item-32-1', text: 'RTK Query baseApi token refresh works on 401', status: 'pending' },
      { id: 'item-32-2', text: 'profileApi queries cache and invalidate correctly', status: 'pending' },
      { id: 'item-32-3', text: 'socialApi toggleFollow mutation with optimistic update works', status: 'pending' },
      { id: 'item-32-4', text: 'listingsApi search/filter queries cache correctly', status: 'pending' },
      { id: 'item-32-5', text: 'addressesApi CRUD operations invalidate correct tags', status: 'pending' },
      { id: 'item-32-6', text: 'paymentCardsApi CRUD operations work', status: 'pending' },
      { id: 'item-32-7', text: 'browsingHistoryApi queries work', status: 'pending' },
      { id: 'item-32-8', text: 'categoriesApi caching works', status: 'pending' },
      { id: 'item-32-9', text: 'dashboardApi seller stats load correctly', status: 'pending' },
      { id: 'item-32-10', text: 'Optimistic updates: Wishlist add/remove instant UI', status: 'pending' },
      { id: 'item-32-11', text: 'Optimistic updates: Follow/unfollow instant UI', status: 'pending' },
      { id: 'item-32-12', text: 'Pagination with serializeQueryArgs works', status: 'pending' },
      { id: 'item-32-13', text: 'Cache resets completely on logout', status: 'pending' },
      { id: 'item-32-14', text: 'Error states from API show user-friendly toast messages', status: 'pending' },
      { id: 'item-32-15', text: 'Loading states from queries handled in components', status: 'pending' },
      { id: 'item-32-16', text: 'Offline mode handled gracefully (no crash)', status: 'pending' },
      { id: 'item-32-17', text: 'Retry mechanism works on network errors', status: 'pending' },
    ],
  },
  {
    id: 'cl-33',
    title: '🔒 Security & Storage',
    items: [
      { id: 'item-33-1', text: 'API keys not exposed in source code', status: 'pending' },
      { id: 'item-33-2', text: 'Tokens stored in EncryptedStorage (not AsyncStorage)', status: 'pending' },
      { id: 'item-33-3', text: 'HTTPS used for all API calls', status: 'pending' },
      { id: 'item-33-4', text: 'JWT decode works for token inspection', status: 'pending' },
      { id: 'item-33-5', text: 'AsyncStorage persists non-sensitive data correctly', status: 'pending' },
      { id: 'item-33-6', text: 'EncryptedStorage persists sensitive data correctly', status: 'pending' },
      { id: 'item-33-7', text: 'Redux state persists where needed (redux-thunk)', status: 'pending' },
      { id: 'item-33-8', text: 'No data loss on app kill/restart', status: 'pending' },
      { id: 'item-33-9', text: 'No debug logs in production build', status: 'pending' },
      { id: 'item-33-10', text: 'Sentry does not capture sensitive user data', status: 'pending' },
    ],
  },
  {
    id: 'cl-34',
    title: '🐛 Error Handling & Edge Cases',
    items: [
      { id: 'item-34-1', text: 'ErrorBoundary catches component crashes', status: 'pending' },
      { id: 'item-34-2', text: 'All API error states show UI feedback', status: 'pending' },
      { id: 'item-34-3', text: 'Error messages are user-friendly (not raw API errors)', status: 'pending' },
      { id: 'item-34-4', text: 'Network errors show retry option', status: 'pending' },
      { id: 'item-34-5', text: 'Form validation errors highlight fields correctly', status: 'pending' },
      { id: 'item-34-6', text: 'No crashes on null/undefined data', status: 'pending' },
      { id: 'item-34-7', text: 'Empty state screens display when no data', status: 'pending' },
      { id: 'item-34-8', text: 'Long text truncates gracefully (ShortNamer)', status: 'pending' },
      { id: 'item-34-9', text: 'Image loading failures show placeholder', status: 'pending' },
      { id: 'item-34-10', text: 'WebSocket disconnect/reconnect handled (chat, bidding)', status: 'pending' },
      { id: 'item-34-11', text: 'MemoryManager prevents memory leaks', status: 'pending' },
    ],
  },
  {
    id: 'cl-35',
    title: '⚡ Performance',
    items: [
      { id: 'item-35-1', text: 'App launches within 3 seconds (Splash screen to Home)', status: 'pending' },
      { id: 'item-35-2', text: 'List scrolling is smooth (60fps)', status: 'pending' },
      { id: 'item-35-3', text: 'Images load efficiently via FastImage caching', status: 'pending' },
      { id: 'item-35-4', text: 'Reanimated animations run on native thread (no jank)', status: 'pending' },
      { id: 'item-35-5', text: 'No unnecessary re-renders on screen focus', status: 'pending' },
      { id: 'item-35-6', text: 'MemoryManager keeps memory usage under control', status: 'pending' },
      { id: 'item-35-7', text: 'Image compression reduces upload sizes', status: 'pending' },
      { id: 'item-35-8', text: 'Product carousel renders without frame drops', status: 'pending' },
      { id: 'item-35-9', text: 'Home screen sections render progressively', status: 'pending' },
      { id: 'item-35-10', text: 'RTK Query caching prevents redundant API calls', status: 'pending' },
    ],
  },
  {
    id: 'cl-36',
    title: '📱 Platform-Specific (iOS)',
    items: [
      { id: 'item-36-1', text: 'App works on iOS 13+', status: 'pending' },
      { id: 'item-36-2', text: 'Tested on iPhone (various sizes)', status: 'pending' },
      { id: 'item-36-3', text: 'Tested on iPad', status: 'pending' },
      { id: 'item-36-4', text: 'Push notifications work on iOS (FCM + APNS)', status: 'pending' },
      { id: 'item-36-5', text: 'Apple Sign-In works', status: 'pending' },
      { id: 'item-36-6', text: 'Apple Pay works in checkout', status: 'pending' },
      { id: 'item-36-7', text: 'Camera permissions requested correctly (Info.plist)', status: 'pending' },
      { id: 'item-36-8', text: 'Location permissions requested correctly', status: 'pending' },
      { id: 'item-36-9', text: 'Photo library permissions work', status: 'pending' },
      { id: 'item-36-10', text: 'Native stack navigator works (iOS preferred)', status: 'pending' },
      { id: 'item-36-11', text: 'App icons and splash screens correct', status: 'pending' },
      { id: 'item-36-12', text: 'Keyboard avoidance works in forms', status: 'pending' },
    ],
  },
  {
    id: 'cl-37',
    title: '📱 Platform-Specific (Android)',
    items: [
      { id: 'item-37-1', text: 'App works on Android 8+', status: 'pending' },
      { id: 'item-37-2', text: 'Tested on various Android screen sizes', status: 'pending' },
      { id: 'item-37-3', text: 'Tested on various Android versions', status: 'pending' },
      { id: 'item-37-4', text: 'Push notifications work on Android (FCM)', status: 'pending' },
      { id: 'item-37-5', text: 'Google Sign-In works', status: 'pending' },
      { id: 'item-37-6', text: 'Google Pay works in checkout', status: 'pending' },
      { id: 'item-37-7', text: 'Camera permissions requested correctly', status: 'pending' },
      { id: 'item-37-8', text: 'Location permissions requested correctly', status: 'pending' },
      { id: 'item-37-9', text: 'Storage permissions work for media', status: 'pending' },
      { id: 'item-37-10', text: 'JS Stack navigator works (Android preferred)', status: 'pending' },
      { id: 'item-37-11', text: 'Hardware back button behavior correct on all screens', status: 'pending' },
      { id: 'item-37-12', text: 'App icons and splash screens correct', status: 'pending' },
      { id: 'item-37-13', text: 'ProGuard rules correct (no crash in release)', status: 'pending' },
      { id: 'item-37-14', text: 'Keyboard avoidance works in forms', status: 'pending' },
    ],
  },
  {
    id: 'cl-38',
    title: '📊 Analytics & Monitoring',
    items: [
      { id: 'item-38-1', text: 'Firebase Analytics events fire correctly', status: 'pending' },
      { id: 'item-38-2', text: 'Screen views tracked on navigation', status: 'pending' },
      { id: 'item-38-3', text: 'User actions tracked (tracking service)', status: 'pending' },
      { id: 'item-38-4', text: 'Conversion events tracked (purchase, listing created)', status: 'pending' },
      { id: 'item-38-5', text: 'Sentry crash reporting configured and working', status: 'pending' },
      { id: 'item-38-6', text: 'Sentry captures errors with proper context', status: 'pending' },
      { id: 'item-38-7', text: 'Performance monitoring enabled', status: 'pending' },
      { id: 'item-38-8', text: 'Source maps uploaded for production builds', status: 'pending' },
    ],
  },
  {
    id: 'cl-39',
    title: '🏗️ Build & Configuration',
    items: [
      { id: 'item-39-1', text: 'Production build (iOS) created successfully', status: 'pending' },
      { id: 'item-39-2', text: 'Production build (Android) created successfully', status: 'pending' },
      { id: 'item-39-3', text: 'Version number incremented (currently 0.2.1)', status: 'pending' },
      { id: 'item-39-4', text: 'Build number incremented', status: 'pending' },
      { id: 'item-39-5', text: 'Bundle identifier/package name correct', status: 'pending' },
      { id: 'item-39-6', text: 'Signing certificates valid', status: 'pending' },
      { id: 'item-39-7', text: 'Environment variables point to production API', status: 'pending' },
      { id: 'item-39-8', text: 'Debug mode disabled in release', status: 'pending' },
      { id: 'item-39-9', text: 'No console.log statements in production', status: 'pending' },
      { id: 'item-39-10', text: 'No debug/test code left in production', status: 'pending' },
      { id: 'item-39-11', text: 'React Native 0.76.3 running stable', status: 'pending' },
    ],
  },
  {
    id: 'cl-40',
    title: '🧪 End-to-End Testing Flows',
    items: [
      { id: 'item-40-1', text: 'E2E: New user signup → onboarding → browse → first purchase', status: 'pending' },
      { id: 'item-40-2', text: 'E2E: Login → browse products → add to wishlist → buy now → checkout → order', status: 'pending' },
      { id: 'item-40-3', text: 'E2E: Create standard listing → publish → view on home → receive offer → accept', status: 'pending' },
      { id: 'item-40-4', text: 'E2E: Create vehicle listing → publish → buyer views → buyer purchases', status: 'pending' },
      { id: 'item-40-5', text: 'E2E: Create real estate listing (V3) → publish → buyer views → buyer contacts', status: 'pending' },
      { id: 'item-40-6', text: 'E2E: Browse auction → place bid → win auction → checkout', status: 'pending' },
      { id: 'item-40-7', text: 'E2E: Make offer on product → seller accepts → buyer checkout', status: 'pending' },
      { id: 'item-40-8', text: 'E2E: Purchase → receive order → initiate return → complete return', status: 'pending' },
      { id: 'item-40-9', text: 'E2E: Message seller → negotiate → purchase', status: 'pending' },
      { id: 'item-40-10', text: 'E2E: Complete profile setup → address → payment card → seller verification', status: 'pending' },
      { id: 'item-40-11', text: 'E2E: Switch language (EN→AR) → verify RTL layout → switch back', status: 'pending' },
      { id: 'item-40-12', text: 'E2E: Buyer/Seller mode switch → verify tab content changes', status: 'pending' },
      { id: 'item-40-13', text: 'Tested on physical iOS device', status: 'pending' },
      { id: 'item-40-14', text: 'Tested on physical Android device', status: 'pending' },
      { id: 'item-40-15', text: 'Tested with slow network (3G)', status: 'pending' },
      { id: 'item-40-16', text: 'Tested with no network (offline mode)', status: 'pending' },
      { id: 'item-40-17', text: 'Tested with airplane mode toggle', status: 'pending' },
      { id: 'item-40-18', text: 'Long session testing (1+ hours, no memory issues)', status: 'pending' },
    ],
  },
  {
    id: 'cl-41',
    title: '📦 App Store & Release',
    items: [
      { id: 'item-41-1', text: 'App Store Connect configured', status: 'pending' },
      { id: 'item-41-2', text: 'App description and metadata ready', status: 'pending' },
      { id: 'item-41-3', text: 'Screenshots for all required iOS sizes', status: 'pending' },
      { id: 'item-41-4', text: 'Privacy policy URL provided', status: 'pending' },
      { id: 'item-41-5', text: 'Support URL provided', status: 'pending' },
      { id: 'item-41-6', text: 'Age rating configured correctly', status: 'pending' },
      { id: 'item-41-7', text: 'TestFlight build tested by team', status: 'pending' },
      { id: 'item-41-8', text: 'Play Console configured', status: 'pending' },
      { id: 'item-41-9', text: 'Play Store description and metadata ready', status: 'pending' },
      { id: 'item-41-10', text: 'Play Store screenshots ready', status: 'pending' },
      { id: 'item-41-11', text: 'Feature graphic ready', status: 'pending' },
      { id: 'item-41-12', text: 'Content rating complete', status: 'pending' },
      { id: 'item-41-13', text: 'Internal testing track tested', status: 'pending' },
      { id: 'item-41-14', text: 'Release notes finalized', status: 'pending' },
    ],
  },
];
